// AUTO-GENERATED by scripts/generate-client-branding-map.ts. Do not edit.
// Sources: lib/branding/clients/*.json. Regenerate via `bun run generate:branding`.
//
// Deploy-overlay seam (ID-68 PC-33-A / DEPLOY-OVERLAY-DESIGN Option 2):
// a client deploy overlays private client JSON into lib/branding/clients/
// BEFORE this prestep runs, so the glob picks it up with no source edit.
// With no overlay present the loader resolves the "default" entry.

import branding0 from '@/lib/branding/clients/default.json';

export const CLIENT_BRANDING_MAP: Record<string, unknown> = {
  "default": branding0,
};
