import { describe, it, expect, beforeAll } from 'vitest';
import { createMockMcpServer } from '@/__tests__/helpers/mcp-server';
import { registerTools } from '@/lib/mcp/tools';
import {
  formatContentItem,
  type ContentItemDetail,
} from '@/lib/mcp/formatters/content';
import {
  formatSearchResults,
  formatQASearchResults,
  type SearchResult,
} from '@/lib/mcp/formatters/search';
import {
  formatIntelligenceSummary,
  type IntelligenceSummaryData,
} from '@/lib/mcp/formatters/intelligence';

// ---------------------------------------------------------------------------
// ID-71.21 — AI-invisibility (B-INV-39) + outputSchema forward-standard
// (B-INV-37) invariant-level coverage.
//
// The per-entry suites (find-tool, content-consolidation, dedup-consolidation,
// where-are-we-exposed-tool, whats-in-my-queue-tool) already assert that each
// NEW consolidated entry from {71.7}/{71.8}/{71.9}/{71.10} carries (or, for the
// two z.union entries, intentionally defers) an `outputSchema`. This suite owns
// the two CROSS-CUTTING invariants that no per-entry suite owns:
//
//   B-INV-39 (PRODUCT.md §E.39, ⇐ SYNTHESIS §1.3 ai-visibility-policy):
//     AI-driven enrichments (classification, summarisation, intelligence
//     scoring) present on CONSUMPTION surfaces as NATIVE data — the platform
//     behaves as if the data was always there. *Fail:* a consumption surface
//     advertises an AI enrichment as a feature ("AI generated this", model
//     attribution, enrichment-lineage framing). The admin Provenance surface is
//     the only carve-out, and it is not a consumption read formatter.
//
//   B-INV-37 (PRODUCT.md §E.37, ⇐ RESEARCH §5.2 / bl-26):
//     `outputSchema` is the forward standard for NEW entries ONLY. *Fail:* a
//     retiring/changing tool is retrofitted, or a new entry omits it where it
//     clearly fits.
//
// Behaviour-first per test-philosophy.md: B-INV-39 asserts on the OBSERVABLE
// rendered markdown a consumption surface returns (the bytes an MCP client
// shows the user); B-INV-37 asserts on the OBSERVABLE registered tool config
// (the `outputSchema` slot the MCP SDK reads at registration), exercised
// through the public `registerTools` registration pathway — not handler
// internals.
// ---------------------------------------------------------------------------

// AI-advertising / enrichment-lineage phrases that MUST NOT appear on any
// consumption surface. Matched case-insensitively against rendered markdown.
const AI_ADVERTISING_PATTERNS: RegExp[] = [
  /\bAI[- ]generated\b/i,
  /\bAI[- ]powered\b/i,
  /\bAI[- ]driven\b/i,
  /\bAI[- ]assisted\b/i,
  /\bAI[- ]suggested\b/i,
  /\bgenerated by (?:AI|Claude|the model|an? (?:language )?model)\b/i,
  /\benriched by AI\b/i,
  /\bAI enrichment\b/i,
  /\busing claude\b/i,
  /\bvia (?:AI|Claude)\b/i,
  /\bmachine[- ]generated\b/i,
  // Model-attribution footer ("…using claude-…", "model: claude-…").
  /\busing\s+claude-/i,
  /\bmodel:\s*claude/i,
];

function expectPresentsEnrichmentsAsNative(label: string, markdown: string) {
  for (const pattern of AI_ADVERTISING_PATTERNS) {
    expect(
      pattern.test(markdown),
      `${label} consumption surface must present enrichments as native, ` +
        `not advertise AI (matched ${pattern}). B-INV-39.`,
    ).toBe(false);
  }
}

// ---------------------------------------------------------------------------
// Fixtures — enriched content, the way the DB stores it after classification /
// summarisation / intelligence scoring has run.
// ---------------------------------------------------------------------------

function makeEnrichedItem(
  overrides: Partial<ContentItemDetail> = {},
): ContentItemDetail {
  return {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    title: 'ISO 9001 Quality Manual',
    suggested_title: 'ISO 9001 Quality Manual (2026 revision)',
    content_type: 'policy',
    primary_domain: 'compliance',
    primary_subtopic: 'quality-management',
    summary: 'A summary of the quality management system requirements.',
    ai_keywords: ['ISO 9001', 'quality', 'audit'],
    freshness: 'current',
    classification_confidence: 0.92,
    source_url: 'https://example.test/iso-9001',
    content: 'The quality management system shall be documented...',
    created_at: '2026-05-01T10:00:00.000Z',
    updated_at: '2026-06-10T09:00:00.000Z',
    governance_review_status: 'approved',
    priority: 'high',
    ...overrides,
  };
}

function makeSearchResult(overrides: Partial<SearchResult> = {}): SearchResult {
  return {
    id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    title: 'Data Retention Policy',
    suggested_title: null,
    content_type: 'policy',
    primary_domain: 'compliance',
    primary_subtopic: 'data-protection',
    summary: 'A summary describing the retention periods for personal data.',
    similarity: 0.87,
    ...overrides,
  };
}

function makeIntelligenceData(
  overrides: Partial<IntelligenceSummaryData> = {},
): IntelligenceSummaryData {
  return {
    workspace_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    workspace_name: 'UK Public Sector',
    period: '7d',
    period_label: 'Last 7 days',
    total_ingested: 120,
    total_passed: 18,
    total_filtered: 102,
    filter_ratio: 0.85,
    by_category: { procurement: 10, policy: 8 },
    by_source: [{ source_name: 'Gov.uk', article_count: 60, passed_count: 12 }],
    top_articles: [
      {
        id: 'd4e5f6a7-b8c9-0123-def1-234567890123',
        title: 'New procurement framework announced',
        source_name: 'Gov.uk',
        external_url: 'https://example.test/article',
        relevance_score: 0.88,
        relevance_category: 'high',
        ai_summary:
          'The framework introduces new thresholds for SME suppliers.',
        matched_categories: ['procurement'],
        published_at: '2026-06-18T08:00:00.000Z',
        ingested_at: '2026-06-19T08:00:00.000Z',
      },
    ],
    unresolved_flags: 0,
    ...overrides,
  };
}

// ===========================================================================
// B-INV-39 — consumption surfaces present AI enrichments as native data
// ===========================================================================

describe('B-INV-39 — AI-invisibility on consumption surfaces', () => {
  it('`get` (content item detail) presents classification + summary as native fields', () => {
    const markdown = formatContentItem(makeEnrichedItem());

    // The enrichment-derived fields are present as plain, native data...
    expect(markdown).toContain('## Summary');
    expect(markdown).toContain(
      'A summary of the quality management system requirements.',
    );
    expect(markdown).toContain('**Domain:** compliance > quality-management');
    expect(markdown).toContain('**Keywords:** ISO 9001, quality, audit');
    // ...with NO AI-advertising framing around them.
    expectPresentsEnrichmentsAsNative('get', markdown);
  });

  it('`get` does not label the summary or keywords as an AI product', () => {
    const markdown = formatContentItem(makeEnrichedItem());
    // Native field labels, not "AI Summary" / "AI Keywords".
    expect(markdown).not.toMatch(/##\s*AI\s+Summary/i);
    expect(markdown).not.toMatch(/\*\*AI\s+Keywords:/i);
    expect(markdown).not.toMatch(/\bClassified by\b/i);
  });

  it('`find` search results present AI summary + AI classification as native', () => {
    const markdown = formatSearchResults('data retention', [
      makeSearchResult(),
    ]);

    expect(markdown).toContain(
      'A summary describing the retention periods for personal data.',
    );
    expect(markdown).toContain('**Domain:** compliance > data-protection');
    // Relevance is the vector-similarity score, surfaced as a plain metric.
    expect(markdown).toContain('**Relevance:** 87%');
    expectPresentsEnrichmentsAsNative('find', markdown);
  });

  it('`find` Q&A results present the AI-generated summary as native', () => {
    const markdown = formatQASearchResults('data retention', [
      makeSearchResult(),
    ]);
    expect(markdown).toContain(
      'A summary describing the retention periods for personal data.',
    );
    expectPresentsEnrichmentsAsNative('find (q&a)', markdown);
  });

  it('intelligence summary presents AI scoring + AI summary as native', () => {
    const markdown = formatIntelligenceSummary(makeIntelligenceData());

    // The AI relevance score renders as a native badge (HIGH/MED/LOW + %)...
    expect(markdown).toContain('[HIGH 88%]');
    // ...and the per-article AI summary renders as plain body text, with no
    // "AI summary:" label or model attribution.
    expect(markdown).toContain(
      'The framework introduces new thresholds for SME suppliers.',
    );
    expect(markdown).not.toMatch(/\bAI\s+summary:/i);
    expectPresentsEnrichmentsAsNative('intelligence summary', markdown);
  });

  it('renders cleanly when a content item has not yet been enriched (no fabricated AI framing)', () => {
    const markdown = formatContentItem(
      makeEnrichedItem({
        summary: null,
        ai_keywords: null,
        classification_confidence: null,
        primary_domain: null,
        primary_subtopic: null,
      }),
    );
    // No summary section is invented, and nothing advertises AI absence either.
    expect(markdown).not.toContain('## Summary');
    expectPresentsEnrichmentsAsNative('get (unenriched)', markdown);
  });
});

// ===========================================================================
// B-INV-37 — outputSchema is the forward standard for NEW entries only
// ===========================================================================

describe('B-INV-37 — outputSchema forward-standard (new consolidated entries only)', () => {
  let toolsWithOutputSchema: Set<string>;
  let registeredNames: Set<string>;

  beforeAll(async () => {
    const mockServer = createMockMcpServer();
    await registerTools(mockServer.server);
    registeredNames = new Set(mockServer.toolList.map((t) => t.name));
    toolsWithOutputSchema = new Set(
      mockServer.toolList
        .filter((t) => t.config.outputSchema !== undefined)
        .map((t) => t.name),
    );
  });

  // The four NEW outcome-shaped consolidated entries from {71.7-71.10} that
  // CAN carry an object outputSchema (i.e. excludes the two z.union entries).
  const NEW_OBJECT_SCHEMA_ENTRIES = [
    'get', // {71.10} — get one-or-many
    'assign', // {71.10} — assign one-or-many
    'where_are_we_exposed', // {71.8}  — five-layer exposure
    'whats_in_my_queue', // {71.9}  — faceted queue
  ] as const;

  // `find`'s response is a z.union — outputSchema is intentionally DEFERRED
  // (the MCP SDK's normalizeObjectSchema() returns undefined for unions,
  // crashing validateToolOutput on undefined._zod). `find_duplicates` is no
  // longer a union itself (ID-131.15, G-DEDUP legacy dedup-family
  // retirement, S446, removed the sibling `scope: 'all'` branch that made
  // it one) but still omits outputSchema — kept minimal-footprint rather
  // than retrofitted, consistent with the other entries in this group. This
  // is the documented "where it fits" exclusion, not a B-INV-37 miss.
  const NEW_UNION_SCHEMA_ENTRIES = ['find', 'find_duplicates'] as const;

  // Retiring/changing ("refine"-verdict) tools that survived the {71}
  // consolidation: they MUST NOT be retrofitted with outputSchema (B-INV-37
  // *Fail* clause). Sourced from RESEARCH.md §4 keep-concept/refine verdicts.
  const RETIRING_OR_CHANGING_TOOLS = [
    'classify_content', // refine — apply §5 grounding standard
    'generate_summary', // refine — output_config.format (§5)
    'get_intelligence_summary', // refine — per-persona so-what consumption read
    'get_entity_relationships', // refine — promote to ontology-grounding affordance
    'get_reorientation', // refine — widen beyond KH state
    'suggest_content_creation', // refine — resolution affordance of exposure
    'create_content_item', // refine — track external-folder-canonical reality
    'get_form_question', // refine + rename — form-question
    'cite_content', // refine — align description post-rename
    'list_active_procurement', // refine — under completing-forms
    'get_procurement_detail', // refine — under completing-forms
  ] as const;

  it('every new object-schema consolidated entry declares an outputSchema', () => {
    for (const name of NEW_OBJECT_SCHEMA_ENTRIES) {
      expect(
        registeredNames.has(name),
        `consolidated entry ${name} must be registered`,
      ).toBe(true);
      expect(
        toolsWithOutputSchema.has(name),
        `new entry ${name} must declare an outputSchema (B-INV-37 forward standard)`,
      ).toBe(true);
    }
  });

  it('find and find_duplicates intentionally omit outputSchema', () => {
    for (const name of NEW_UNION_SCHEMA_ENTRIES) {
      expect(
        registeredNames.has(name),
        `consolidated entry ${name} must be registered`,
      ).toBe(true);
      expect(
        toolsWithOutputSchema.has(name),
        `${name} must NOT declare an outputSchema — see NEW_UNION_SCHEMA_ENTRIES comment above`,
      ).toBe(false);
    }
  });

  it('no retiring/changing tool is retrofitted with an outputSchema', () => {
    for (const name of RETIRING_OR_CHANGING_TOOLS) {
      if (!registeredNames.has(name)) continue; // tolerant if a tool later retires fully
      expect(
        toolsWithOutputSchema.has(name),
        `retiring/changing tool ${name} must NOT be retrofitted with an ` +
          `outputSchema (B-INV-37 *Fail* clause)`,
      ).toBe(false);
    }
  });
});
