/**
 * Verifies that the MCP `review_item` prompt template injects the governance
 * skill content from `lib/ai/skills/governance.md` into the prompt text that
 * is delivered to external LLM clients (Claude Desktop / Claude.ai).
 *
 * This test deliberately uses the REAL `loadSkill` loader (no mock) so that
 * it asserts the actual file contents flow into the prompt. The skill file is
 * small and read from disk, so this is feasible and meaningful.
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { registerPrompts } from '@/lib/mcp/resources';
import { createMockMcpServer } from '@/__tests__/helpers/mcp-server';

describe('MCP review_item prompt — governance skill wiring', () => {
  let server: ReturnType<typeof createMockMcpServer>;

  beforeEach(() => {
    server = createMockMcpServer();
    // registerPrompts is synchronous; the per-prompt handler is async.
    registerPrompts(server.server as never);
  });

  it('registers a review_item prompt', () => {
    const prompt = server.getPrompt('review_item');
    expect(prompt).toBeDefined();
    expect(prompt!.config.title).toBe('Review Content Item');
  });

  it('inlines the governance skill freshness lifecycle definitions', async () => {
    const prompt = server.getPrompt('review_item');
    expect(prompt).toBeDefined();

    const result = await prompt!.handler({
      item_id: '11111111-1111-4111-8111-111111111111',
    });
    const text = result.messages[0]?.content.text ?? '';

    // The governance skill defines the four freshness states and the four
    // lifecycle types. These strings live in `lib/ai/skills/governance.md`
    // and must reach the LLM verbatim through the prompt template.
    expect(text).toContain('fresh → aging → stale → expired');
    expect(text).toContain('Evergreen');
    expect(text).toContain('Date-Bound');
    expect(text).toContain('Regulation');
    expect(text).toContain('Bid-Discovered');
  });

  it('inlines the governance principles and review triggers', async () => {
    const prompt = server.getPrompt('review_item');
    const result = await prompt!.handler({
      item_id: '22222222-2222-4222-8222-222222222222',
    });
    const text = result.messages[0]?.content.text ?? '';

    // Governance principles and review trigger definitions.
    expect(text).toContain('Observe and intervene');
    expect(text).toContain('Quality score < 60');
    expect(text).toContain('Classification confidence < 0.5');
  });

  it('contains the governance skill heading and key sections verbatim', async () => {
    // Skill content is inlined at build time via
    // `lib/ai/skills/inlined.generated.ts` (regenerated by
    // `scripts/generate-skills-inline.ts`). Markdown prose may be reflowed
    // independently of regeneration cadence, so we assert the structural
    // headings and unambiguous lifecycle-trigger sentences rather than the
    // entire file verbatim — those carry the load-bearing semantics that the
    // LLM consumes.
    const skillPath = join(
      process.cwd(),
      'lib',
      'ai',
      'skills',
      'governance.md',
    );
    const realSkill = readFileSync(skillPath, 'utf-8');

    const prompt = server.getPrompt('review_item');
    const result = await prompt!.handler({
      item_id: '33333333-3333-4333-8333-333333333333',
    });
    const text = result.messages[0]?.content.text ?? '';

    // Sanity: the on-disk file is non-empty.
    expect(realSkill.length).toBeGreaterThan(0);

    // Load-bearing headings and definitions that must be present regardless
    // of paragraph wrapping.
    expect(text).toContain('# Governance Skill');
    expect(text).toContain('## Freshness Lifecycle');
    expect(text).toContain('## Lifecycle Types and Thresholds');
    expect(text).toContain('## Quality Scoring');
    expect(text).toContain('## Review Triggers');
    expect(text).toContain('## Governance Principles');

    // Single-line lifecycle threshold rows (immune to prose wrapping).
    expect(text).toContain('**Fresh:** < 12 months');
    expect(text).toContain('**Expired:** > 24 months');
    expect(text).toContain('**Fresh:** > 3 months until expiry');
    expect(text).toContain('**Expired:** Past expiry date');
  });

  it('still includes the per-item review instructions and item id', async () => {
    const prompt = server.getPrompt('review_item');
    const itemId = '44444444-4444-4444-8444-444444444444';
    const result = await prompt!.handler({ item_id: itemId });
    const text = result.messages[0]?.content.text ?? '';

    expect(text).toContain(itemId);
    expect(text).toContain('get_content_item');
    // Confirms the prompt asks the LLM to APPLY the governance content rather
    // than ignore it.
    expect(text).toContain('governance');
  });
});
