// AUTO-GENERATED by scripts/generate-content-type-values.ts. Do not edit.
// Source: __tests__/fixtures/ontology/ontology-cv-baselines.json (content_type cv, baseline_values[].key).
// Regenerate via `bun run generate:content-type-values`.
//
// Inlined at build time so the closed content_type enum is available to
// client bundles without dragging node:fs through lib/ontology/loader.ts.
// The markdown-parity test (`__tests__/lib/ontology/markdown-parity.test.ts`)
// asserts this list, the markdown register, and the live DB CHECK
// constraint stay in lockstep.

export const CONTENT_TYPE_VALUES: readonly string[] = Object.freeze([
  "article",
  "blog",
  "pdf",
  "note",
  "research",
  "document",
  "other",
] as const);
