/**
 * form_type triple-source parity guard (ID-52.6 / TECH §2.6b).
 *
 * Real-behaviour: loads the actual `26-form-type.md` via `loadOntologyCVs()`
 * and the actual `scripts/tests/fixtures/taxonomy_snapshot.json:form_types`
 * array, then asserts the two key sets agree exactly.
 *
 * This is the TS half of the form_type triple-source lockstep:
 *   - Live `form_types` Postgres table (source of truth)
 *   - `docs/ontology/26-form-type.md` baseline_values (TS / markdown consumer)
 *   - `scripts/tests/fixtures/taxonomy_snapshot.json:form_types` (Python consumer)
 *
 * The snapshot is regenerated by `bun run sync:taxonomy` from the live table;
 * this test asserts the markdown side stays in lockstep. The Python side is
 * guarded by `scripts/tests/test_cocoindex_extraction.py::TestFormTypeParity`
 * (frozenset loaded from snapshot vs snapshot dict).
 *
 * Spec: `docs/specs/id-52-form-extraction/TECH.md` §2.6b;
 * `docs/specs/id-52-form-extraction/PLAN.md` Phase 1 / {52.6}.
 */
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

import { loadOntologyCVs } from '@/lib/ontology/loader';

const PROJECT_ROOT = join(__dirname, '../../..');
const SNAPSHOT_PATH = join(
  PROJECT_ROOT,
  'scripts/tests/fixtures/taxonomy_snapshot.json',
);
const FORM_TYPE_MD_PATH = join(PROJECT_ROOT, 'docs/ontology/26-form-type.md');

/**
 * Parse the `## Baseline values` prose table key column from raw markdown.
 *
 * Reads the file as text (NOT via `loadOntologyCVs`, which parses only the
 * YAML frontmatter) so that the human-readable prose table — an unguarded
 * surface per RESEARCH R6 — is held in lockstep with the frontmatter
 * `baseline_values`. Returns the first-column keys of every body row under
 * the `## Baseline values` heading, in document order.
 */
function parseBaselineValuesProseKeys(markdown: string): string[] {
  const lines = markdown.split('\n');
  const headingIdx = lines.findIndex(
    (line) => line.trim() === '## Baseline values',
  );
  if (headingIdx === -1) return [];

  const keys: string[] = [];
  for (let i = headingIdx + 1; i < lines.length; i += 1) {
    const line = lines[i];
    // Stop at the next section heading.
    if (line.startsWith('## ')) break;
    const trimmed = line.trim();
    if (!trimmed.startsWith('|')) continue;
    const cells = trimmed
      .split('|')
      .slice(1, -1)
      .map((cell) => cell.trim());
    if (cells.length === 0) continue;
    const key = cells[0];
    // Skip the header row (`key`) and the markdown separator row (`---`).
    if (key === 'key' || /^:?-{2,}:?$/.test(key)) continue;
    if (key.length === 0) continue;
    keys.push(key);
  }
  return keys;
}

interface FormTypeRow {
  key: string;
  label: string;
}

interface TaxonomySnapshot {
  form_types?: FormTypeRow[];
}

describe('form_type triple-source parity (TECH §2.6b)', () => {
  it('taxonomy_snapshot.json includes a non-empty form_types array', () => {
    expect(existsSync(SNAPSHOT_PATH)).toBe(true);
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    expect(Array.isArray(snapshot.form_types)).toBe(true);
    expect(snapshot.form_types!.length).toBeGreaterThan(0);
  });

  it('every form_types entry exposes a string key and string label', () => {
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    for (const row of snapshot.form_types ?? []) {
      expect(typeof row.key).toBe('string');
      expect(row.key.length).toBeGreaterThan(0);
      expect(typeof row.label).toBe('string');
      expect(row.label.length).toBeGreaterThan(0);
    }
  });

  it('26-form-type.md baseline_values keys match taxonomy_snapshot.json:form_types keys exactly', () => {
    const cvs = loadOntologyCVs();
    const formTypeCV = cvs.find((cv) => cv.cv_name === 'form_type');
    expect(
      formTypeCV,
      'docs/ontology/26-form-type.md must define cv_name=form_type',
    ).toBeDefined();

    const mdKeys = (formTypeCV!.baseline_values ?? [])
      .map((bv) => bv.key)
      .sort();

    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    const snapshotKeys = (snapshot.form_types ?? [])
      .map((row) => row.key)
      .sort();

    const missingFromSnapshot = mdKeys.filter((k) => !snapshotKeys.includes(k));
    const missingFromMarkdown = snapshotKeys.filter((k) => !mdKeys.includes(k));

    expect(
      { missingFromSnapshot, missingFromMarkdown },
      `form_type triple-source drift:\n` +
        `  In markdown but missing from snapshot: ${missingFromSnapshot.join(', ') || '(none)'}\n` +
        `  In snapshot but missing from markdown: ${missingFromMarkdown.join(', ') || '(none)'}`,
    ).toEqual({ missingFromSnapshot: [], missingFromMarkdown: [] });

    expect(mdKeys).toEqual(snapshotKeys);
  });

  it('26-form-type.md prose `## Baseline values` table keys match frontmatter baseline_values keys exactly', () => {
    const markdown = readFileSync(FORM_TYPE_MD_PATH, 'utf8');
    const proseKeys = parseBaselineValuesProseKeys(markdown).sort();

    const cvs = loadOntologyCVs();
    const formTypeCV = cvs.find((cv) => cv.cv_name === 'form_type');
    expect(
      formTypeCV,
      'docs/ontology/26-form-type.md must define cv_name=form_type',
    ).toBeDefined();
    const frontmatterKeys = (formTypeCV!.baseline_values ?? [])
      .map((bv) => bv.key)
      .sort();

    const inProseNotFrontmatter = proseKeys.filter(
      (k) => !frontmatterKeys.includes(k),
    );
    const inFrontmatterNotProse = frontmatterKeys.filter(
      (k) => !proseKeys.includes(k),
    );

    expect(
      { inProseNotFrontmatter, inFrontmatterNotProse },
      `form_type prose/frontmatter drift:\n` +
        `  In prose table but missing from frontmatter: ${inProseNotFrontmatter.join(', ') || '(none)'}\n` +
        `  In frontmatter but missing from prose table: ${inFrontmatterNotProse.join(', ') || '(none)'}`,
    ).toEqual({ inProseNotFrontmatter: [], inFrontmatterNotProse: [] });

    expect(proseKeys).toEqual(frontmatterKeys);
  });
});
