/**
 * form_type dual-source parity guard (ID-52.6 / TECH §2.6b; repointed at
 * ID-68.27 OQ-E branch (b)).
 *
 * Real-behaviour: loads the frozen form_type baseline from
 * `__tests__/fixtures/ontology/ontology-cv-baselines.json` and the actual
 * `scripts/tests/fixtures/taxonomy_snapshot.json:form_types` array, then
 * asserts the two key sets agree exactly.
 *
 * History: the TS side of this guard originally read the live
 * `docs/ontology/26-form-type.md`. The ontology CV register went fully
 * private at the ID-68.27 OQ-E branch-(b) cutover (live home:
 * `${KH_PRIVATE_DOCS_DIR}/src/content/docs/ontology/`), so the ratified
 * baseline_values block is frozen in the fixture instead. The lockstep is
 * now:
 *   - Live `form_types` Postgres table (source of truth)
 *   - `__tests__/fixtures/ontology/ontology-cv-baselines.json` (TS-side
 *     frozen baseline — this file)
 *   - `scripts/tests/fixtures/taxonomy_snapshot.json:form_types` (Python
 *     consumer; regenerated by `bun run sync:taxonomy` from the live table)
 *
 * The prose-table ↔ frontmatter parity half of the original guard moved
 * conceptually to the private docs-site repo with the live register (the
 * "parity-guard twin" follow-up recorded in the ID-68.27 journal). The
 * Python side remains guarded by
 * `scripts/tests/test_cocoindex_extraction.py::TestFormTypeParity`.
 *
 * Spec: `id-52-form-extraction/TECH.md` §2.6b; ID-68.27 record holdback (b),
 * branch (b) ratified S324.
 */
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

import { OntologyCVSchema } from '@/lib/ontology/schemas';

const PROJECT_ROOT = join(__dirname, '../../..');
const SNAPSHOT_PATH = join(
  PROJECT_ROOT,
  'scripts/tests/fixtures/taxonomy_snapshot.json',
);
const BASELINES_PATH = join(
  PROJECT_ROOT,
  '__tests__/fixtures/ontology/ontology-cv-baselines.json',
);

interface FormTypeRow {
  key: string;
  label: string;
}

interface TaxonomySnapshot {
  form_types?: FormTypeRow[];
}

interface CVBaselinesFixture {
  cvs: Array<{
    cv_name: string;
    baseline_values?: Array<{ key: string }>;
  }>;
}

describe('form_type dual-source parity (TECH §2.6b, fixture-based per ID-68.27 OQ-E (b))', () => {
  it('taxonomy_snapshot.json includes a non-empty form_types array', () => {
    expect(existsSync(SNAPSHOT_PATH)).toBe(true);
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    expect(Array.isArray(snapshot.form_types)).toBe(true);
    expect(snapshot.form_types!.length).toBeGreaterThan(0);
  });

  it('every form_types entry exposes a string key and string label', () => {
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    for (const row of snapshot.form_types ?? []) {
      expect(typeof row.key).toBe('string');
      expect(row.key.length).toBeGreaterThan(0);
      expect(typeof row.label).toBe('string');
      expect(row.label.length).toBeGreaterThan(0);
    }
  });

  it('the frozen form_type baseline validates against the ontology CV schema', () => {
    const fixture = JSON.parse(
      readFileSync(BASELINES_PATH, 'utf8'),
    ) as CVBaselinesFixture;
    const formTypeCV = fixture.cvs.find((cv) => cv.cv_name === 'form_type');
    expect(
      formTypeCV,
      'ontology-cv-baselines.json must define cv_name=form_type',
    ).toBeDefined();

    const result = OntologyCVSchema.safeParse(formTypeCV);
    expect(
      result.success,
      result.success
        ? ''
        : result.error.issues
            .map((i) => `${i.path.join('.')}: ${i.message}`)
            .join('\n'),
    ).toBe(true);
  });

  it('frozen form_type baseline keys match taxonomy_snapshot.json:form_types keys exactly', () => {
    const fixture = JSON.parse(
      readFileSync(BASELINES_PATH, 'utf8'),
    ) as CVBaselinesFixture;
    const formTypeCV = fixture.cvs.find((cv) => cv.cv_name === 'form_type');
    expect(
      formTypeCV,
      'ontology-cv-baselines.json must define cv_name=form_type',
    ).toBeDefined();

    const fixtureKeys = (formTypeCV!.baseline_values ?? [])
      .map((bv) => bv.key)
      .sort();

    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    const snapshotKeys = (snapshot.form_types ?? [])
      .map((row) => row.key)
      .sort();

    const missingFromSnapshot = fixtureKeys.filter(
      (k) => !snapshotKeys.includes(k),
    );
    const missingFromFixture = snapshotKeys.filter(
      (k) => !fixtureKeys.includes(k),
    );

    expect(
      { missingFromSnapshot, missingFromFixture },
      `form_type dual-source drift:\n` +
        `  In fixture but missing from snapshot: ${missingFromSnapshot.join(', ') || '(none)'}\n` +
        `  In snapshot but missing from fixture: ${missingFromFixture.join(', ') || '(none)'}\n` +
        `Update the fixture per its _meta.update_protocol (live register: private docs-site repo).`,
    ).toEqual({ missingFromSnapshot: [], missingFromFixture: [] });

    expect(fixtureKeys).toEqual(snapshotKeys);
  });
});
