/**
 * form_type triple-source parity guard (ID-52.6 / TECH §2.6b).
 *
 * Real-behaviour: loads the actual `26-form-type.md` via `loadOntologyCVs()`
 * and the actual `scripts/tests/fixtures/taxonomy_snapshot.json:form_types`
 * array, then asserts the two key sets agree exactly.
 *
 * This is the TS half of the form_type triple-source lockstep:
 *   - Live `form_types` Postgres table (source of truth)
 *   - `docs/ontology/26-form-type.md` baseline_values (TS / markdown consumer)
 *   - `scripts/tests/fixtures/taxonomy_snapshot.json:form_types` (Python consumer)
 *
 * The snapshot is regenerated by `bun run sync:taxonomy` from the live table;
 * this test asserts the markdown side stays in lockstep. The Python side is
 * guarded by `scripts/tests/test_cocoindex_extraction.py::TestFormTypeParity`
 * (frozenset loaded from snapshot vs snapshot dict).
 *
 * Spec: `docs/specs/id-52-form-extraction/TECH.md` §2.6b;
 * `docs/specs/id-52-form-extraction/PLAN.md` Phase 1 / {52.6}.
 */
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

import { loadOntologyCVs } from '@/lib/ontology/loader';

const PROJECT_ROOT = join(__dirname, '../../..');
const SNAPSHOT_PATH = join(
  PROJECT_ROOT,
  'scripts/tests/fixtures/taxonomy_snapshot.json',
);

interface FormTypeRow {
  key: string;
  label: string;
}

interface TaxonomySnapshot {
  form_types?: FormTypeRow[];
}

describe('form_type triple-source parity (TECH §2.6b)', () => {
  it('taxonomy_snapshot.json includes a non-empty form_types array', () => {
    expect(existsSync(SNAPSHOT_PATH)).toBe(true);
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    expect(Array.isArray(snapshot.form_types)).toBe(true);
    expect(snapshot.form_types!.length).toBeGreaterThan(0);
  });

  it('every form_types entry exposes a string key and string label', () => {
    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    for (const row of snapshot.form_types ?? []) {
      expect(typeof row.key).toBe('string');
      expect(row.key.length).toBeGreaterThan(0);
      expect(typeof row.label).toBe('string');
      expect(row.label.length).toBeGreaterThan(0);
    }
  });

  it('26-form-type.md baseline_values keys match taxonomy_snapshot.json:form_types keys exactly', () => {
    const cvs = loadOntologyCVs();
    const formTypeCV = cvs.find((cv) => cv.cv_name === 'form_type');
    expect(
      formTypeCV,
      'docs/ontology/26-form-type.md must define cv_name=form_type',
    ).toBeDefined();

    const mdKeys = (formTypeCV!.baseline_values ?? [])
      .map((bv) => bv.key)
      .sort();

    const snapshot = JSON.parse(
      readFileSync(SNAPSHOT_PATH, 'utf8'),
    ) as TaxonomySnapshot;
    const snapshotKeys = (snapshot.form_types ?? [])
      .map((row) => row.key)
      .sort();

    const missingFromSnapshot = mdKeys.filter((k) => !snapshotKeys.includes(k));
    const missingFromMarkdown = snapshotKeys.filter((k) => !mdKeys.includes(k));

    expect(
      { missingFromSnapshot, missingFromMarkdown },
      `form_type triple-source drift:\n` +
        `  In markdown but missing from snapshot: ${missingFromSnapshot.join(', ') || '(none)'}\n` +
        `  In snapshot but missing from markdown: ${missingFromMarkdown.join(', ') || '(none)'}`,
    ).toEqual({ missingFromSnapshot: [], missingFromMarkdown: [] });

    expect(mdKeys).toEqual(snapshotKeys);
  });
});
