'use client';

import { Layers, Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { DigestDomainSection } from '@/components/digest-domain-section';
import { DigestExportMenu } from '@/components/digest-export-menu';
import { formatDate } from '@/lib/format';
import { digestTypeLabel } from '@/lib/digest-export';
import type { Digest } from '@/types/digest';
import { cn } from '@/lib/utils';

interface DigestViewProps {
  digest: Digest;
  className?: string;
}

export function DigestView({ digest, className }: DigestViewProps) {
  return (
    <div className={cn('space-y-8', className)}>
      {/* Header */}
      <header className="space-y-3">
        <div className="flex flex-wrap items-center gap-3">
          <h1 className="text-fluid-2xl font-bold tracking-tight">
            {digestTypeLabel(digest.digest_type)}
          </h1>
          <Badge variant="secondary" className="text-sm font-normal">
            {digest.item_count} {digest.item_count === 1 ? 'item' : 'items'}
          </Badge>
          <div className="ml-auto flex items-center gap-2" data-no-print>
            <DigestExportMenu digest={digest} />
          </div>
        </div>
        <p className="text-sm text-muted-foreground">
          {formatDate(digest.period_start)} &ndash;{' '}
          {formatDate(digest.period_end)}
          {digest.generated_by && (
            <span className="ml-2">
              &middot; Generated by {digest.generated_by}
            </span>
          )}
        </p>
      </header>

      {/* Narrative summary */}
      {digest.narrative_summary && (
        <section className="rounded-xl border border-border bg-card p-6">
          <div className="mb-3 flex items-center gap-2">
            <Sparkles className="size-4 text-primary" />
            <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              Summary
            </h2>
          </div>
          <div className="space-y-4 text-[15px] leading-relaxed text-foreground/90">
            {digest.narrative_summary.split('\n\n').map((paragraph, i) => (
              <p key={i}>{paragraph}</p>
            ))}
          </div>
        </section>
      )}

      {/* Domain sections */}
      {digest.domain_summaries.length > 0 && (
        <section>
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            By Domain
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {digest.domain_summaries.map((ds) => (
              <DigestDomainSection key={ds.domain} domainSummary={ds} />
            ))}
          </div>
        </section>
      )}

      {/* Theme clusters */}
      {digest.theme_clusters.length > 0 && (
        <section className="rounded-xl border border-border bg-card p-6">
          <div className="mb-4 flex items-center gap-2">
            <Layers className="size-4 text-primary" />
            <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              Cross-Domain Themes
            </h2>
          </div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {digest.theme_clusters.map((cluster) => (
              <div
                key={cluster.theme}
                className="rounded-lg border border-border bg-background p-4"
              >
                <div className="flex items-start justify-between gap-2">
                  <h3 className="text-sm font-semibold text-foreground">
                    {cluster.theme}
                  </h3>
                  <Badge variant="outline" className="shrink-0 text-[11px]">
                    {cluster.item_count}
                  </Badge>
                </div>
                <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
                  {cluster.description}
                </p>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
