"""Shared pytest fixtures for KB pipeline tests."""

import json
import os

import pytest

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
SNAPSHOT_PATH = os.path.join(FIXTURE_DIR, "taxonomy_snapshot.json")


@pytest.fixture(scope="session")
def taxonomy_from_snapshot():
    """Load taxonomy from committed snapshot file.

    The snapshot is generated by `bun run sync:taxonomy` and committed to the
    repo. This avoids requiring a live DB connection for unit tests while still
    using current taxonomy data.
    """
    with open(SNAPSHOT_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def valid_domains(taxonomy_from_snapshot):
    """Active domain names from the taxonomy snapshot."""
    return taxonomy_from_snapshot["domains"]


@pytest.fixture(scope="session")
def valid_subtopics(taxonomy_from_snapshot):
    """Active subtopic names from the taxonomy snapshot."""
    return taxonomy_from_snapshot["subtopics"]
