/**
 * Bundle MCP App HTML files into importable TypeScript string constants.
 *
 * Reads the built single-file HTML from each MCP App's dist/ directory and
 * generates lib/mcp/app-bundles.ts with the HTML as exported string constants.
 * This allows the MCP server to serve app resources on Vercel serverless
 * without filesystem reads.
 *
 * Usage: bun run scripts/bundle-mcp-apps.ts
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const PROJECT_ROOT = join(import.meta.dirname, '..');
const OUTPUT_PATH = join(PROJECT_ROOT, 'lib', 'mcp', 'app-bundles.ts');

interface AppConfig {
  name: string;
  constName: string;
  htmlPath: string;
}

const APPS: AppConfig[] = [
  {
    name: 'coverage-matrix',
    constName: 'COVERAGE_MATRIX_HTML',
    htmlPath: join(
      PROJECT_ROOT,
      'mcp-apps',
      'coverage-matrix',
      'dist',
      'app.html',
    ),
  },
  {
    name: 'bid-dashboard',
    constName: 'BID_DASHBOARD_HTML',
    htmlPath: join(
      PROJECT_ROOT,
      'mcp-apps',
      'bid-dashboard',
      'dist',
      'app.html',
    ),
  },
  {
    name: 'reorient-me',
    constName: 'REORIENT_ME_HTML',
    htmlPath: join(PROJECT_ROOT, 'mcp-apps', 'reorient-me', 'dist', 'app.html'),
  },
  {
    name: 'intelligence-feed',
    constName: 'INTELLIGENCE_FEED_HTML',
    htmlPath: join(
      PROJECT_ROOT,
      'mcp-apps',
      'intelligence-feed',
      'dist',
      'app.html',
    ),
  },
];

/** Escape a string for safe embedding in a JS template literal */
function escapeForTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function main(): Promise<void> {
  const lines: string[] = [
    '/**',
    ' * Auto-generated MCP App HTML bundles.',
    ' * DO NOT EDIT — regenerated by scripts/bundle-mcp-apps.ts',
    ' * Run: bun run build:mcp-apps',
    ' */',
    '',
  ];

  for (const app of APPS) {
    try {
      const html = await readFile(app.htmlPath, 'utf-8');
      const escaped = escapeForTemplateLiteral(html);
      lines.push(`export const ${app.constName} = \`${escaped}\`;`);
      console.log(`✓ ${app.name}: ${html.length} chars`);
    } catch {
      lines.push(`export const ${app.constName}: string | null = null;`);
      console.log(`○ ${app.name}: not built (exported null)`);
    }
    lines.push('');
  }

  await writeFile(OUTPUT_PATH, lines.join('\n'));
  console.log(`\nWritten to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error('Failed to bundle MCP apps:', err);
  process.exit(1);
});
