#!/usr/bin/env bun
/**
 * Codegen: read the frozen ontology CV baseline fixture
 * (__tests__/fixtures/ontology/ontology-cv-baselines.json) and write
 * lib/ontology/content-type-values.generated.ts exporting the closed
 * content_type enum as a static readonly tuple.
 *
 * Why: lib/ontology/loader.ts uses synchronous node:fs at module init
 * to validate the full 29-file CV register. That import chain
 *   loader → content-type-registry → validation/schemas → bid-context-provider
 * transitively pulled node:fs into the client browser bundle, which
 * Next.js 16 Turbopack rejects with "the chunking context (unknown) does
 * not support external modules (request: node:fs)". Inlining at build
 * time eliminates the runtime FS read on the registry path while
 * leaving the loader available for server-only consumers (tests,
 * parity guard).
 *
 * Source history: this script originally parsed the
 * docs/ontology/04-content-type.md frontmatter. The public
 * docs/ontology/ register went fully private at the ID-68.27 OQ-E
 * branch-(b) cutover (live home: the private docs-site repo via
 * KH_PRIVATE_DOCS_DIR), so the script now reads the frozen public
 * parity fixture instead. The fixture is kept in lockstep with the live
 * register + DB CHECK constraint by
 * `__tests__/lib/ontology/markdown-parity.test.ts`
 * (update protocol: the fixture's `_meta.update_protocol`).
 *
 * Run via `bun run generate:content-type-values`. Wired as `prebuild`
 * + `predev` so the generated file is always fresh.
 */
import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';

const ROOT = process.cwd();
const SOURCE = join(
  ROOT,
  '__tests__',
  'fixtures',
  'ontology',
  'ontology-cv-baselines.json',
);
const OUTPUT = join(
  ROOT,
  'lib',
  'ontology',
  'content-type-values.generated.ts',
);

interface BaselineValue {
  key: string;
  label: string;
  provenance: string;
}

interface BaselineFixture {
  cvs?: Array<{
    cv_name: string;
    baseline_values?: BaselineValue[];
  }>;
}

async function main(): Promise<void> {
  const raw = await readFile(SOURCE, 'utf-8');
  const fixture = JSON.parse(raw) as BaselineFixture;

  const contentType = (fixture.cvs ?? []).find(
    (cv) => cv.cv_name === 'content_type',
  );
  if (!contentType) {
    throw new Error(
      `[generate-content-type-values] ${SOURCE} has no cv with cv_name: content_type`,
    );
  }

  const values = contentType.baseline_values;
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error(
      `[generate-content-type-values] ${SOURCE} content_type cv has no baseline_values`,
    );
  }

  const keys = values.map((bv) => bv.key);
  const tuple = keys.map((k) => `  ${JSON.stringify(k)},`).join('\n');

  const out = `// AUTO-GENERATED by scripts/generate-content-type-values.ts. Do not edit.
// Source: __tests__/fixtures/ontology/ontology-cv-baselines.json (content_type cv, baseline_values[].key).
// Regenerate via \`bun run generate:content-type-values\`.
//
// Inlined at build time so the closed content_type enum is available to
// client bundles without dragging node:fs through lib/ontology/loader.ts.
// The markdown-parity test (\`__tests__/lib/ontology/markdown-parity.test.ts\`)
// asserts this list, the markdown register, and the live DB CHECK
// constraint stay in lockstep.

export const CONTENT_TYPE_VALUES: readonly string[] = Object.freeze([
${tuple}
] as const);
`;

  await writeFile(OUTPUT, out, 'utf-8');
  console.log(
    `[generate-content-type-values] wrote ${OUTPUT} (${keys.length} values)`,
  );
}

main().catch((err) => {
  console.error('[generate-content-type-values] failed:', err);
  process.exit(1);
});
