#!/usr/bin/env bun
/**
 * Codegen: read every lib/ai/skills/*.md and write
 * lib/ai/skills/inlined.generated.ts exporting them as a string map.
 *
 * Why: at Vercel runtime, `__dirname`-based filesystem reads of skills
 * .md files fail with ENOENT because Next.js bundles the loader into a
 * serverless chunk that does not sit next to the static .md files.
 * `outputFileTracingIncludes` did not reliably copy them either (App
 * Router source-path glob does not match the route output paths).
 * Inlining the markdown at build time eliminates the runtime FS read.
 *
 * Run via `bun run generate:skills`. Wired as `prebuild` + `predev` so
 * the generated file is always fresh.
 */
import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';

const SKILLS_DIR = join(process.cwd(), 'lib', 'ai', 'skills');
const OUTPUT = join(SKILLS_DIR, 'inlined.generated.ts');

async function main(): Promise<void> {
  const files = (await readdir(SKILLS_DIR))
    .filter((f) => f.endsWith('.md'))
    .sort();

  if (files.length === 0) {
    throw new Error(`No skill .md files found in ${SKILLS_DIR}`);
  }

  const entries: Array<[string, string]> = [];
  for (const file of files) {
    const name = file.replace(/\.md$/, '');
    const content = await readFile(join(SKILLS_DIR, file), 'utf-8');
    entries.push([name, content]);
  }

  const body = entries
    .map(
      ([name, content]) =>
        `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`,
    )
    .join('\n');

  const out = `// AUTO-GENERATED by scripts/generate-skills-inline.ts. Do not edit.
// Sources: lib/ai/skills/*.md. Regenerate via \`bun run generate:skills\`.
// Inlined at build time so Vercel serverless functions never need to read
// .md files from disk (which fails with ENOENT due to bundled-chunk
// path resolution).

export const SKILLS: Readonly<Record<string, string>> = {
${body}
};
`;

  await writeFile(OUTPUT, out, 'utf-8');
  const total = entries.reduce((acc, [, c]) => acc + c.length, 0);
  console.log(
    `[generate-skills-inline] wrote ${OUTPUT} (${entries.length} skills, ${total.toLocaleString()} chars)`,
  );
}

main().catch((err) => {
  console.error('[generate-skills-inline] failed:', err);
  process.exit(1);
});
