#!/usr/bin/env bun
/**
 * Codegen: read docs/ontology/04-content-type.md and write
 * lib/ontology/content-type-values.generated.ts exporting the closed
 * content_type enum as a static readonly tuple.
 *
 * Why: lib/ontology/loader.ts uses synchronous node:fs at module init
 * to validate the full 29-file CV register. That import chain
 *   loader → content-type-registry → validation/schemas → bid-context-provider
 * transitively pulled node:fs into the client browser bundle, which
 * Next.js 16 Turbopack rejects with "the chunking context (unknown) does
 * not support external modules (request: node:fs)". Inlining at build
 * time eliminates the runtime FS read on the registry path while
 * leaving the loader available for server-only consumers (tests,
 * parity guard).
 *
 * Run via `bun run generate:content-type-values`. Wired as `prebuild`
 * + `predev` so the generated file is always fresh. The
 * markdown-parity test continues to assert the markdown register and
 * the live DB CHECK constraint remain in lockstep.
 */
import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import matter from 'gray-matter';

const ROOT = process.cwd();
const SOURCE = join(ROOT, 'docs', 'ontology', '04-content-type.md');
const OUTPUT = join(
  ROOT,
  'lib',
  'ontology',
  'content-type-values.generated.ts',
);

interface BaselineValue {
  key: string;
  label: string;
  provenance: string;
}

interface ContentTypeFrontmatter {
  cv_name?: string;
  baseline_values?: BaselineValue[];
}

async function main(): Promise<void> {
  const raw = await readFile(SOURCE, 'utf-8');
  const fm = matter(raw).data as ContentTypeFrontmatter;

  if (fm.cv_name !== 'content_type') {
    throw new Error(
      `[generate-content-type-values] ${SOURCE} must declare cv_name: content_type (got ${String(fm.cv_name)})`,
    );
  }

  const values = fm.baseline_values;
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error(
      `[generate-content-type-values] ${SOURCE} has no baseline_values`,
    );
  }

  const keys = values.map((bv) => bv.key);
  const tuple = keys.map((k) => `  ${JSON.stringify(k)},`).join('\n');

  const out = `// AUTO-GENERATED by scripts/generate-content-type-values.ts. Do not edit.
// Source: docs/ontology/04-content-type.md (baseline_values[].key).
// Regenerate via \`bun run generate:content-type-values\`.
//
// Inlined at build time so the closed content_type enum is available to
// client bundles without dragging node:fs through lib/ontology/loader.ts.
// The markdown-parity test (\`__tests__/lib/ontology/markdown-parity.test.ts\`)
// asserts this list, the markdown register, and the live DB CHECK
// constraint stay in lockstep.

export const CONTENT_TYPE_VALUES: readonly string[] = Object.freeze([
${tuple}
] as const);
`;

  await writeFile(OUTPUT, out, 'utf-8');
  console.log(
    `[generate-content-type-values] wrote ${OUTPUT} (${keys.length} values)`,
  );
}

main().catch((err) => {
  console.error('[generate-content-type-values] failed:', err);
  process.exit(1);
});
