#!/usr/bin/env bun
/**
 * Codegen: glob every lib/branding/clients/*.json and write
 * lib/branding/client-branding-map.generated.ts exporting them as the
 * CLIENT_BRANDING_MAP consumed by lib/client-config.ts.
 *
 * Why (ID-68 PC-33-A / DEPLOY-OVERLAY-DESIGN Option 2 — deploy-overlay
 * seam): the branding map was previously a hand-maintained literal with
 * static imports, so every client config was compiled into the public
 * bundle and adding/removing a client meant editing source. Generating
 * the map from the directory contents means a client deploy only ever
 * ADDS files (lib/branding/clients/<id>.json + public/clients/<id>/*)
 * via a private overlay before the build prestep runs — no source
 * patching. With no overlay present the map regenerates from the
 * tracked clients only and the loader falls back to `default`
 * (DEPLOY-OVERLAY §6 no-overlay regression guard).
 *
 * Run via `bun run generate:branding`. Wired as `prebuild` + `predev`
 * and chained in `build:vercel` so the generated file is always fresh.
 * Mirrors the scripts/generate-skills-inline.ts codegen idiom.
 */
import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const CLIENTS_DIR = join(process.cwd(), 'lib', 'branding', 'clients');
const OUTPUT = join(
  process.cwd(),
  'lib',
  'branding',
  'client-branding-map.generated.ts',
);

/** File basenames (without .json) of every client config in the dir, sorted. */
export function listClientIds(files: string[]): string[] {
  return files
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort();
}

/**
 * Render the generated module source for the given client ids.
 * Pure function of the id list — deterministic (sorted) output so the
 * public build is reproducible and the overlay only ever ADDS entries.
 */
export function renderClientBrandingMap(clientIds: string[]): string {
  const ids = [...clientIds].sort();

  if (!ids.includes('default')) {
    throw new Error(
      `lib/branding/clients/default.json is required — the loader falls back to the "default" entry when a client id is absent from the map. Found: [${ids.join(', ')}]`,
    );
  }

  for (const id of ids) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) {
      throw new Error(
        `Client id "${id}" is not a valid slug ([a-z0-9-], leading alphanumeric) — the codegen emits it as an import path and map key.`,
      );
    }
  }

  const imports = ids
    .map(
      (id, i) =>
        `import branding${i} from '@/lib/branding/clients/${id}.json';`,
    )
    .join('\n');
  const entries = ids
    .map((id, i) => `  ${JSON.stringify(id)}: branding${i},`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-client-branding-map.ts. Do not edit.
// Sources: lib/branding/clients/*.json. Regenerate via \`bun run generate:branding\`.
//
// Deploy-overlay seam (ID-68 PC-33-A / DEPLOY-OVERLAY-DESIGN Option 2):
// a client deploy overlays private client JSON into lib/branding/clients/
// BEFORE this prestep runs, so the glob picks it up with no source edit.
// With no overlay present the loader resolves the "default" entry.

${imports}

export const CLIENT_BRANDING_MAP: Record<string, unknown> = {
${entries}
};
`;
}

async function main(): Promise<void> {
  const files = await readdir(CLIENTS_DIR);
  const ids = listClientIds(files);
  const out = renderClientBrandingMap(ids);
  await writeFile(OUTPUT, out, 'utf-8');
  console.log(
    `[generate-client-branding-map] wrote ${OUTPUT} (${ids.length} client${ids.length === 1 ? '' : 's'}: ${ids.join(', ')})`,
  );
}

// Guard so importing the exported helpers (e.g. from Vitest) does not run
// the codegen side-effect — only direct CLI invocation does.
if (process.argv[1]?.includes('generate-client-branding-map')) {
  main().catch((err) => {
    console.error('[generate-client-branding-map] failed:', err);
    process.exit(1);
  });
}
