-- =============================================================================
-- ID-61 Unit E — DB co-migration of the bid -> procurement/form rename
-- =============================================================================
--
-- STRATEGY.md §2 Item 1 + §2 "DB residue". Three independent changes, all in
-- the public schema (the api layer is generator-owned — see note below):
--
--   1. public.get_aggregate_win_rate_stats — RETURNS TABLE column
--      `unique_bids` -> `unique_procurements`, and the body-only CTE alias
--      `bid_outcome` -> `outcome`. CREATE OR REPLACE is safe because the
--      RETURNS-TABLE shape change is positional (column renamed, type/order
--      unchanged) and callers read positionally.
--
--   2. public.bid_response_auto_version() -> public.form_response_auto_version():
--      CREATE the renamed trigger function (body verbatim), repoint the
--      `form_response_set_version` trigger on form_responses to the new
--      function, mirror the GRANT/REVOKE, then DROP the old function. Zero TS
--      callers (internal trigger function).
--
--   3. public.get_form_summary(bid_workspace_id uuid) -> (workspace_id uuid):
--      CREATE OR REPLACE with the renamed parameter + the six body references.
--      No TS named-arg callers (PostgREST positional) — verified zero
--      `rpc('get_form_summary', { bid_workspace_id })` in the TS corpus.
--
-- api-LAYER NOTE: the api.get_aggregate_win_rate_stats wrapper is normally
-- GENERATED by scripts/generate-api-views.ts (it introspects
-- pg_get_function_result of the public function and re-emits the wrapper into
-- 20260623140000_id115_api_views_and_rpcs.sql). It IS hand-authored here in
-- block 1 because the public function needs DROP+CREATE (the RETURNS-TABLE
-- column rename triggers SQLSTATE 42P13 under CREATE OR REPLACE), and the api
-- wrapper depends on the public function — so this migration MUST drop the api
-- wrapper first and recreate it, otherwise the migration would leave the DB
-- with a dropped public fn and a dangling/dropped api wrapper. The recreated
-- api wrapper mirrors the id115 generated form verbatim except the renamed
-- column. Post-cutover the Orchestrator re-runs generate-api-views.ts, which
-- re-emits this api wrapper BYTE-IDENTICALLY (it introspects the now-
-- unique_procurements public fn), so the `generate-api-views --check` drift
-- guard stays green. See the cutover runbook returned with this Subtask.
--
-- Function discipline (supabase/CLAUDE.md): every (re)created function pins
-- `SET search_path = public, extensions`; the new trigger function mirrors the
-- original's explicit REVOKE … FROM PUBLIC + GRANT … TO service_role.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. public.get_aggregate_win_rate_stats — unique_bids -> unique_procurements
--    (RETURNS TABLE column) + bid_outcome -> outcome (body-only CTE alias).
--
--    DROP+CREATE (NOT CREATE OR REPLACE): PostgreSQL forbids renaming a
--    RETURNS-TABLE output column via CREATE OR REPLACE (SQLSTATE 42P13 — "cannot
--    change return type of existing function"). The api wrapper depends on the
--    public function (SELECT * FROM public.get_aggregate_win_rate_stats()), so
--    drop the api wrapper FIRST, then the public function, then recreate both.
--    Verified the api wrapper is the SOLE dependent — no view / function /
--    trigger else references the public fn — so DROP without CASCADE is clean.
--    Both DROPs clear the function grants, so the original grants are RE-EMITTED
--    after each CREATE (public: squash L12454-56; api: id115 L1546-47).
-- -----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS "api"."get_aggregate_win_rate_stats"();
DROP FUNCTION IF EXISTS "public"."get_aggregate_win_rate_stats"();

CREATE FUNCTION "public"."get_aggregate_win_rate_stats"() RETURNS TABLE("scope" "text", "total_citations" bigint, "winning_citations" bigint, "losing_citations" bigint, "pending_citations" bigint, "win_rate" numeric, "unique_items_cited" bigint, "unique_procurements" bigint)
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'extensions'
    AS $$
BEGIN
  RETURN QUERY

  WITH citation_detail AS (
    SELECT
      ci.primary_domain,
      cc.cited_content_item_id,
      cc.citing_form_response_id,
      bq.workspace_id,
      w.domain_metadata->>'outcome' as outcome
    FROM public.citations cc
    JOIN content_items ci ON ci.id = cc.cited_content_item_id
    JOIN form_responses br ON br.id = cc.citing_form_response_id
    JOIN form_questions bq ON bq.id = br.question_id
    JOIN workspaces w ON w.id = bq.workspace_id
    WHERE cc.cited_kind = 'content_item'
  ),
  domain_stats AS (
    SELECT
      primary_domain as scope,
      COUNT(*)::bigint as total_citations,
      COUNT(*) FILTER (WHERE outcome = 'won')::bigint as winning_citations,
      COUNT(*) FILTER (WHERE outcome = 'lost')::bigint as losing_citations,
      COUNT(*) FILTER (WHERE outcome IS NULL
                        OR outcome NOT IN ('won', 'lost', 'withdrawn'))::bigint as pending_citations,
      CASE
        WHEN COUNT(*) FILTER (WHERE outcome IN ('won', 'lost')) > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE outcome = 'won')::numeric /
            COUNT(*) FILTER (WHERE outcome IN ('won', 'lost'))::numeric,
            2
          )
        ELSE 0
      END as win_rate,
      COUNT(DISTINCT cited_content_item_id)::bigint as unique_items_cited,
      COUNT(DISTINCT workspace_id)::bigint as unique_procurements
    FROM citation_detail
    GROUP BY primary_domain
  ),
  overall AS (
    SELECT
      'overall'::text as scope,
      COUNT(*)::bigint as total_citations,
      COUNT(*) FILTER (WHERE outcome = 'won')::bigint as winning_citations,
      COUNT(*) FILTER (WHERE outcome = 'lost')::bigint as losing_citations,
      COUNT(*) FILTER (WHERE outcome IS NULL
                        OR outcome NOT IN ('won', 'lost', 'withdrawn'))::bigint as pending_citations,
      CASE
        WHEN COUNT(*) FILTER (WHERE outcome IN ('won', 'lost')) > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE outcome = 'won')::numeric /
            COUNT(*) FILTER (WHERE outcome IN ('won', 'lost'))::numeric,
            2
          )
        ELSE 0
      END as win_rate,
      COUNT(DISTINCT cited_content_item_id)::bigint as unique_items_cited,
      COUNT(DISTINCT workspace_id)::bigint as unique_procurements
    FROM citation_detail
  )
  SELECT * FROM overall
  UNION ALL
  SELECT * FROM domain_stats
  ORDER BY scope;
END;
$$;

ALTER FUNCTION "public"."get_aggregate_win_rate_stats"() OWNER TO "postgres";

-- Re-emit the public grants the DROP cleared (squash baseline L12454-56).
REVOKE ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() TO "service_role";

COMMENT ON FUNCTION "public"."get_aggregate_win_rate_stats"() IS 'ID-61 Unit E — overall + per-domain citation win-rate aggregator. RETURNS TABLE column unique_bids renamed to unique_procurements and the body-only CTE alias bid_outcome renamed to outcome (bid->procurement rename). Caller app/api/analytics/win-rate.';

-- Recreate the api wrapper with the renamed column, mirroring the id115
-- generated form verbatim (20260623140000 L1538-47) except unique_bids ->
-- unique_procurements. generate-api-views.ts will re-emit this byte-identically
-- post-cutover (it introspects the now-unique_procurements public fn), so the
-- generate-api-views --check drift guard stays green.
CREATE FUNCTION "api"."get_aggregate_win_rate_stats"()
  RETURNS TABLE(scope text, total_citations bigint, winning_citations bigint, losing_citations bigint, pending_citations bigint, win_rate numeric, unique_items_cited bigint, unique_procurements bigint)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.get_aggregate_win_rate_stats();
$api$;
REVOKE EXECUTE ON FUNCTION "api"."get_aggregate_win_rate_stats"() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION "api"."get_aggregate_win_rate_stats"() TO anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 2. public.bid_response_auto_version() -> public.form_response_auto_version()
--    Create new fn (body verbatim), repoint trigger, mirror grants, drop old.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."form_response_auto_version"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'extensions'
    AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.version := 1;
  ELSIF TG_OP = 'UPDATE' THEN
    -- Only increment if response content actually changed
    IF NEW.response_text IS DISTINCT FROM OLD.response_text
       OR NEW.response_text_advanced IS DISTINCT FROM OLD.response_text_advanced
       OR NEW.metadata IS DISTINCT FROM OLD.metadata THEN
      NEW.version := OLD.version + 1;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."form_response_auto_version"() OWNER TO "postgres";

-- Mirror the original grants (squash baseline L12323-12324).
REVOKE ALL ON FUNCTION "public"."form_response_auto_version"() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."form_response_auto_version"() FROM anon;
GRANT ALL ON FUNCTION "public"."form_response_auto_version"() TO "service_role";

-- Repoint the trigger to the renamed function (CREATE OR REPLACE TRIGGER is
-- idempotent in PG15+; replaces the existing form_response_set_version trigger).
CREATE OR REPLACE TRIGGER "form_response_set_version" BEFORE INSERT OR UPDATE ON "public"."form_responses" FOR EACH ROW EXECUTE FUNCTION "public"."form_response_auto_version"();

-- Drop the old function now that nothing references it (trigger repointed above).
DROP FUNCTION IF EXISTS "public"."bid_response_auto_version"();

-- -----------------------------------------------------------------------------
-- 3. public.get_form_summary(bid_workspace_id uuid) -> (workspace_id uuid)
--    CREATE OR REPLACE with renamed parameter + six body references + grants.
--    Parameter rename requires dropping the old signature first (CREATE OR
--    REPLACE cannot rename an input parameter in place — 42P13).
-- -----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS "public"."get_form_summary"("uuid");

CREATE OR REPLACE FUNCTION "public"."get_form_summary"("workspace_id" "uuid") RETURNS json
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'extensions'
    AS $$
  SELECT json_build_object(
    'workspace_id', workspace_id,
    'total_questions', (SELECT COUNT(*) FROM form_questions WHERE form_questions.workspace_id = get_form_summary.workspace_id),
    'status_breakdown', (
      SELECT json_agg(json_build_object('status', status, 'count', cnt) ORDER BY cnt DESC)
      FROM (SELECT status, COUNT(*) AS cnt FROM form_questions WHERE form_questions.workspace_id = get_form_summary.workspace_id GROUP BY status) sub),
    'confidence_breakdown', (
      SELECT json_agg(json_build_object('posture', confidence_posture, 'count', cnt) ORDER BY cnt DESC)
      FROM (SELECT confidence_posture, COUNT(*) AS cnt FROM form_questions
        WHERE form_questions.workspace_id = get_form_summary.workspace_id AND confidence_posture IS NOT NULL GROUP BY confidence_posture) sub),
    'responses_count', (
      SELECT COUNT(*) FROM form_responses br JOIN form_questions bq ON bq.id = br.question_id WHERE bq.workspace_id = get_form_summary.workspace_id),
    'review_status_breakdown', (
      SELECT json_agg(json_build_object('status', review_status, 'count', cnt) ORDER BY cnt DESC)
      FROM (SELECT br.review_status, COUNT(*) AS cnt FROM form_responses br
        JOIN form_questions bq ON bq.id = br.question_id WHERE bq.workspace_id = get_form_summary.workspace_id GROUP BY br.review_status) sub),
    'sections', (
      SELECT json_agg(json_build_object('section', section_name, 'question_count', cnt, 'completed', completed_cnt) ORDER BY min_seq)
      FROM (SELECT bq.section_name, COUNT(*) AS cnt, COUNT(*) FILTER (WHERE bq.status = 'complete') AS completed_cnt,
        MIN(bq.section_sequence) AS min_seq FROM form_questions bq WHERE bq.workspace_id = get_form_summary.workspace_id GROUP BY bq.section_name) sub)
  );
$$;

ALTER FUNCTION "public"."get_form_summary"("workspace_id" "uuid") OWNER TO "postgres";

-- Mirror the original grants (squash baseline L12592-12594).
REVOKE ALL ON FUNCTION "public"."get_form_summary"("workspace_id" "uuid") FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."get_form_summary"("workspace_id" "uuid") FROM anon;
GRANT ALL ON FUNCTION "public"."get_form_summary"("workspace_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_form_summary"("workspace_id" "uuid") TO "service_role";

COMMENT ON FUNCTION "public"."get_form_summary"("workspace_id" "uuid") IS 'ID-61 Unit E — workspace rollup JSON. Parameter bid_workspace_id renamed to workspace_id (bid->procurement rename); six body references updated. No rpc() named-arg call-sites in the TS corpus (PostgREST positional).';
