-- ID-68.21 — drop the superseded client-named sign-up auth hook.
--
-- The generic, config-driven hook (hook_restrict_signup_to_allowed_domain,
-- migration 20260603121652) has replaced the client-named hook in
-- supabase/config.toml, and the live Before-User-Created auth hook on staging
-- and prod has been repointed to it via the Supabase dashboard (Liam, S330).
-- The client-named function is now orphaned; drop it.
--
-- Append-only / replay-safe: migration 20260424202806 CREATEs this function
-- (so a project reset / branch-from-migrations restores it); this later
-- migration removes it again, leaving the generic hook as the only sign-up
-- gate. IF EXISTS keeps the drop idempotent across reset / rebase / the
-- planned prod+staging wipe-and-recut from the ID-45 re-ingest branch.
--
-- NOTE: this removes the function from the LIVE schema only. The function
-- definition (with the hardcoded @client.example literal) remains in tracked
-- migration history at 20260424202806 — that source-history de-identification
-- is the ID-68.10 / {68.29} history-redaction lane's responsibility, out of
-- scope here.
--
-- Reference: docs/reference/auth-hooks.md ; ID-68 TECH §PC-39(i).

DROP FUNCTION IF EXISTS public.hook_restrict_signup_to_example-client_domain(jsonb);
