-- ID-58 {58.11} — DROP the legacy `public.content_citations` table (LAST in the wave, Inv-25).
--
-- This is the terminal subtask of the ID-58 citations REPLACE wave. All re-points
-- ({58.5}..{58.10}) have already landed:
--   • `update_citation_count()` trigger fn + its two triggers re-pointed onto
--     `public.citations` (the new polymorphic table) by {58.5}.
--   • the four win-rate RPCs re-pointed onto `public.citations` by {58.5}.
--   • all live TS/Python consumers re-pointed off `content_citations` by {58.6}..{58.10}.
--
-- DROP-safety (verified on staging `turayklvaunphgbgscat` immediately before this DROP):
--   • `content_citations` is 0-row (always was — never populated).
--   • NO function definition references `content_citations` (re-points complete).
--   • NO inbound FK constraint targets it; NO view references it.
--   • Its only remaining owned objects are its own indexes
--     (idx_content_citations_item / _response / _created_by), its two count triggers
--     (trg_citation_count_insert / _delete), its toast table and RLS policies — all of
--     which `DROP TABLE` removes automatically. The equivalent count triggers already
--     exist on `public.citations`, so count maintenance is uninterrupted.
--
-- STAGING-ONLY: the production DROP is deferred to the ID-45 public-cutover (Liam-gated).
--
-- Spec slice: PRODUCT Inv-25 (DROP last) + TECH "Migration — DROP last".

DROP TABLE IF EXISTS public.content_citations;
