-- ID-131 {131.32} G-PRE-APPLY-131.13 — residual ingestion_quality_log
-- content_item_id SQL readers, surfaced during {131.31}'s TS consumer sweep
-- and NOT among {131.13}'s (20260703160000) five declared dispositions.
-- {131.13} renamed ingestion_quality_log.content_item_id ->
-- source_document_id (FK re-targets source_documents ON DELETE CASCADE).
--
-- §0 (MOST CRITICAL — read this first): api.ingestion_quality_log.
-- config.toml schemas=["api"] means PostgREST exposes ONLY api.*; every
-- supabase-js `.from('ingestion_quality_log')` call — INCLUDING every
-- {131.31} TS re-point onto source_document_id — resolves to
-- api.ingestion_quality_log at runtime, not the public.* base table
-- (lib/supabase/schema.ts DB_OPTION; ID-115 cutover). api.* views are NOT
-- auto-updated by a base-table RENAME COLUMN the way OTHER dependent
-- objects are: empirically verified (scratch DB) that a view's OWN output
-- column name is fixed at CREATE VIEW time and stays put even after the
-- underlying column it reads is renamed. api.ingestion_quality_log
-- (last regenerated by 20260625160000_id130_api_views_regen.sql) still
-- projects `content_item_id` — so without §1 below, {131.13} applying
-- would leave EVERY api.ingestion_quality_log read/write (all of {131.31}'s
-- re-pointed TS) failing with "column source_document_id does not exist",
-- regardless of how correct the TS/SQL is beneath it. This exact
-- rename-needs-a-companion-api-regen pattern already has a precedent in
-- this codebase: 20260628200000_id131_extract_reparent.sql (M2, {131.8})
-- explicitly called out this consequence and shipped
-- 20260628200001_id131_extract_reparent_api_regen.sql as its companion for
-- the 5 tables it re-parented. §1 here is the SAME companion pattern,
-- scoped to this ONE table, hand-authored from the
-- scripts/generate-api-views.ts bare-column/security_invoker/explicit-grant
-- convention (matching the entity_mentions precedent's own file header).
--
-- FUNCTION bodies (LANGUAGE sql or plpgsql) are a SEPARATE, second class of
-- gap: they are stored as opaque text and re-resolved against the catalog
-- at CALL time — Postgres does not validate their column references at
-- CREATE/ALTER time, so each of the three functions below (§2-§4) would
-- silently keep "working" right up until the first post-apply call, which
-- would then fail with "column content_item_id does not exist". Views
-- (other than the api.* passthrough in §1) are different again: Postgres
-- tracks view->column dependency by attnum, and a column rename
-- automatically updates every dependent view's internal query plan with
-- zero action required for correctness — confirmed via a full corpus sweep
-- that surfaced exactly one more dependent view, public.quality_issues_pending
-- (squash_baseline), NOT touched here because it needs no fix for
-- correctness: it will keep resolving correctly post-apply. (Same
-- fixed-at-CREATE-time caveat as api.ingestion_quality_log applies to ITS
-- own output column too — it stays named content_item_id, a cosmetic
-- mismatch against the value it now holds — but this view has ZERO live TS
-- callers, so unlike §1 there is no runtime consequence. Left as a
-- documented finding for whoever does {131.19}'s full facet pass.)
--
-- Three functions fixed (§2-§4), all with LIVE TS/RPC callers except
-- run_quality_scan:
--   2. get_items_with_quality_flags — hooks/browse/use-browse-data.ts
--      (quality_issues pre-filter + per-item flagged-ids badge query)
--   3. get_quality_issue_counts — app/api/quality/summary/route.ts,
--      lib/mcp/tools/dashboard.ts ("where are we exposed" tool)
--   4. run_quality_scan — zero live callers today (dormant), fixed anyway
--      per explicit instruction rather than left as a landmine for whoever
--      eventually calls it.
--
-- ---------------------------------------------------------------------------
-- §1. api.ingestion_quality_log — companion view regen (see §0 above).
--    Column list otherwise byte-identical to id130_api_views_regen.sql's
--    version; only content_item_id -> source_document_id changes.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS api.ingestion_quality_log;
CREATE VIEW api.ingestion_quality_log WITH (security_invoker = true) AS
  SELECT
    id,
    source_document_id,
    flag_type,
    details,
    resolved,
    created_at,
    severity,
    ingestion_batch,
    resolved_at,
    resolved_by,
    source_url,
    resolution_notes,
    created_by
  FROM public.ingestion_quality_log;
GRANT SELECT ON api.ingestion_quality_log TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.ingestion_quality_log TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.ingestion_quality_log TO service_role;
--
-- §2. get_items_with_quality_flags() — REWRITE, RETURN GRAIN PRESERVED.
--    The naive re-point (SELECT DISTINCT iql.source_document_id ...) would
--    change the function's return grain from content_items.id to
--    source_documents.id, forcing a caller change in
--    hooks/browse/use-browse-data.ts AND colliding with that file's
--    pre-filter id-space: workspaceIds (content_item_workspaces.
--    content_item_id) is content_items.id-keyed, entityMatchIds
--    (entity_mentions.source_document_id) is ALREADY source_documents.id-
--    keyed, and buildBrowseQuery's `idSets` intersection compares them
--    positionally with no id-space reconciliation (a pre-existing,
--    out-of-scope inconsistency whenever workspace+entity filters are
--    combined). Changing quality_issues' grain to source_documents.id
--    would make that latent inconsistency worse for the (currently
--    consistent) workspace+quality_issues combination without fixing the
--    workspace+entity one. Instead: keep content_items driving the query,
--    JOIN ingestion_quality_log via the new source_document_id column, and
--    keep DISTINCT ci.id as the SELECT target. RETURNS SETOF uuid is
--    unchanged; api.get_items_with_quality_flags() is an unchanged
--    passthrough wrapper (`SELECT * FROM public.get_items_with_quality_flags()`)
--    and needs no touch. Zero TS caller changes required.
--    Same content_items:source_document_id many-to-one granularity shift
--    as {131.31} (confirmed non-unique via
--    idx_content_items_source_document_id) — a content_item now shows as
--    "has quality issues" if ANY content_item sharing its source document
--    has an unresolved flag, not just itself. Matches the {131.13}
--    migration's own design intent (ingestion_quality_log re-parented onto
--    source_documents), not introduced here.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."get_items_with_quality_flags"() RETURNS SETOF "uuid"
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'extensions'
    AS $$
    SELECT DISTINCT ci.id
    FROM content_items ci
    JOIN ingestion_quality_log iql ON iql.source_document_id = ci.source_document_id
    WHERE iql.resolved = FALSE
      AND ci.source_document_id IS NOT NULL
      AND ci.archived_at IS NULL;
$$;

COMMENT ON FUNCTION "public"."get_items_with_quality_flags"() IS 'ID-131 {131.32} G-PRE-APPLY-131.13: re-pointed off the dying ingestion_quality_log.content_item_id (renamed to source_document_id by {131.13}) onto a content_items-driven query joined via source_document_id. RETURNS SETOF uuid unchanged (still content_items.id) — no caller change required. Callers: hooks/browse/use-browse-data.ts (quality_issues pre-filter + flagged-ids badge query).';

REVOKE ALL ON FUNCTION "public"."get_items_with_quality_flags"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."get_items_with_quality_flags"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_items_with_quality_flags"() TO "service_role";

-- ---------------------------------------------------------------------------
-- §3. get_quality_issue_counts() — REWRITE. Squash-baseline body, never
--    superseded (the id115/id130 migrations only ever redefined its thin
--    api.* passthrough wrapper). LIVE callers: app/api/quality/summary/
--    route.ts, lib/mcp/tools/dashboard.ts (both consume ONLY
--    flag_type/severity/open_count — no ids — so the return shape is
--    unaffected either way).
--
--    NOT a naive LEFT JOIN content_items ci ON iql.source_document_id =
--    ci.source_document_id: content_items:source_document_id is
--    many-to-one, so a plain JOIN/LEFT JOIN would fan out one
--    ingestion_quality_log row into N rows (one per sibling content_item)
--    and inflate COUNT(*) by that fan-out factor. Rewritten as an EXISTS
--    predicate instead — preserves "one row per flag" cardinality exactly
--    like the original content_item_id-keyed 1:1 join did, while still
--    counting a flag as open only when the SSRF-style NULL
--    source_document_id case applies (unchanged) or at least one sibling
--    content_item is non-archived (replaces the single content_item.id
--    lookup this used to do).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."get_quality_issue_counts"() RETURNS TABLE("flag_type" "text", "severity" "text", "open_count" bigint)
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'extensions'
    AS $$
    SELECT
        iql.flag_type,
        iql.severity,
        COUNT(*) AS open_count
    FROM ingestion_quality_log iql
    WHERE iql.resolved = FALSE
      AND (
        iql.source_document_id IS NULL
        OR EXISTS (
            SELECT 1 FROM content_items ci
            WHERE ci.source_document_id = iql.source_document_id
              AND ci.archived_at IS NULL
        )
      )
    GROUP BY iql.flag_type, iql.severity
    ORDER BY
        CASE iql.severity WHEN 'error' THEN 1 WHEN 'warning' THEN 2 WHEN 'info' THEN 3 END,
        iql.flag_type;
$$;

COMMENT ON FUNCTION "public"."get_quality_issue_counts"() IS 'ID-131 {131.32} G-PRE-APPLY-131.13: re-pointed off the dying ingestion_quality_log.content_item_id (renamed to source_document_id by {131.13}). Rewritten as an EXISTS predicate (not a JOIN) to preserve one-row-per-flag COUNT(*) cardinality against the now many-to-one content_items:source_document_id relationship. RETURNS TABLE shape unchanged. Callers: app/api/quality/summary/route.ts, lib/mcp/tools/dashboard.ts (both consume flag_type/severity/open_count only).';

REVOKE ALL ON FUNCTION "public"."get_quality_issue_counts"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."get_quality_issue_counts"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_quality_issue_counts"() TO "service_role";

-- ---------------------------------------------------------------------------
-- §4. run_quality_scan() — REWRITE. Zero live TS/RPC callers today (confirmed
--    dormant by grep + the bl-46 migration's own "the function has no
--    callers yet" note), but its three INSERT branches (missing_domain,
--    low_confidence, empty_content) all write `ci.id` (content_items.id)
--    into the dying content_item_id column and dedup-guard via a
--    `content_item_id NOT IN (...)` subquery against the same column — a
--    landmine that would error the first time anything ever calls this
--    RPC post-apply, fixed now rather than left for a future caller to
--    discover.
--
--    Re-pointed onto ci.source_document_id (the same content_items ->
--    source_documents resolution used throughout {131.31}/{131.32}); items
--    with no backing source document are skipped (no valid owner document
--    to record the flag against) rather than inserting an orphaned
--    NULL-keyed row. Dedup-guard subqueries re-pointed onto
--    source_document_id in lockstep (still correctly cross-run: a document
--    already flagged on a prior scan is skipped on the next one).
--
--    Each branch also gets `DISTINCT ON (ci.source_document_id) ...
--    ORDER BY ci.source_document_id, ci.id`: content_items:source_document_id
--    is many-to-one, so the original per-content_item SELECT would, within
--    a SINGLE scan run, insert one flag row per sibling content_item
--    sharing a document that matches the same criterion (e.g. two content
--    items from the same document both missing a domain) — a
--    duplicate-row inflation the original 1:1-keyed function never had.
--    DISTINCT ON keeps "one flag row per flagged document per run" and
--    picks the lowest-id sibling's detail fields deterministically; which
--    sibling "wins" the detail payload is immaterial (source_document_id,
--    flag_type, severity, and dedup semantics are unaffected).
--    RETURNS TABLE shape and all four issue_type rows unchanged.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."run_quality_scan"("p_batch_name" "text" DEFAULT ('quality-scan-'::"text" || "to_char"("now"(), 'YYYYMMDD-HH24MISS'::"text"))) RETURNS TABLE("issue_type" "text", "items_found" bigint, "flags_created" bigint)
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'extensions'
    AS $$
DECLARE
    v_missing_domain BIGINT := 0;
    v_missing_domain_flagged BIGINT := 0;
    v_low_confidence BIGINT := 0;
    v_low_confidence_flagged BIGINT := 0;
    v_empty_source_url BIGINT := 0;
    v_empty_content BIGINT := 0;
    v_empty_content_flagged BIGINT := 0;
BEGIN
    -- 1. Missing domain classification
    SELECT COUNT(*) INTO v_missing_domain
    FROM content_items
    WHERE primary_domain IS NULL;

    INSERT INTO ingestion_quality_log (source_document_id, flag_type, severity, details, ingestion_batch)
    SELECT DISTINCT ON (ci.source_document_id)
        ci.source_document_id,
        'classification_low',
        'warning',
        jsonb_build_object(
            'confidence', COALESCE(ci.classification_confidence, 0),
            'reason', 'Missing domain classification',
            'scan_source', 'run_quality_scan'
        ),
        p_batch_name
    FROM content_items ci
    WHERE ci.primary_domain IS NULL
      AND ci.source_document_id IS NOT NULL
      AND ci.source_document_id NOT IN (
          SELECT iql.source_document_id
          FROM ingestion_quality_log iql
          WHERE iql.flag_type = 'classification_low'
            AND iql.resolved = FALSE
            AND iql.source_document_id IS NOT NULL
      )
    ORDER BY ci.source_document_id, ci.id;

    GET DIAGNOSTICS v_missing_domain_flagged = ROW_COUNT;

    -- 2. Low classification confidence (< 0.30)
    SELECT COUNT(*) INTO v_low_confidence
    FROM content_items
    WHERE primary_domain IS NOT NULL
      AND classification_confidence IS NOT NULL
      AND classification_confidence < 0.30;

    INSERT INTO ingestion_quality_log (source_document_id, flag_type, severity, details, ingestion_batch)
    SELECT DISTINCT ON (ci.source_document_id)
        ci.source_document_id,
        'classification_low',
        'info',
        jsonb_build_object(
            'confidence', ci.classification_confidence,
            'domain', ci.primary_domain,
            'subtopic', ci.primary_subtopic,
            'reason', 'Very low classification confidence (< 0.30)',
            'scan_source', 'run_quality_scan'
        ),
        p_batch_name
    FROM content_items ci
    WHERE ci.primary_domain IS NOT NULL
      AND ci.classification_confidence IS NOT NULL
      AND ci.classification_confidence < 0.30
      AND ci.source_document_id IS NOT NULL
      AND ci.source_document_id NOT IN (
          SELECT iql.source_document_id
          FROM ingestion_quality_log iql
          WHERE iql.flag_type = 'classification_low'
            AND iql.resolved = FALSE
            AND iql.source_document_id IS NOT NULL
      )
    ORDER BY ci.source_document_id, ci.id;

    GET DIAGNOSTICS v_low_confidence_flagged = ROW_COUNT;

    -- 3. Empty-string source_url (fix in-place) — UNCHANGED, content_items-only.
    UPDATE content_items
    SET source_url = NULL
    WHERE source_url = '';

    GET DIAGNOSTICS v_empty_source_url = ROW_COUNT;

    UPDATE content_items
    SET source_domain = NULL
    WHERE source_domain = '';

    -- 4. Empty content field
    SELECT COUNT(*) INTO v_empty_content
    FROM content_items
    WHERE content IS NULL OR TRIM(content) = '';

    INSERT INTO ingestion_quality_log (source_document_id, flag_type, severity, details, ingestion_batch)
    SELECT DISTINCT ON (ci.source_document_id)
        ci.source_document_id,
        'missing_content',
        'error',
        jsonb_build_object(
            'reason', 'Content field is empty or NULL',
            'scan_source', 'run_quality_scan'
        ),
        p_batch_name
    FROM content_items ci
    WHERE (ci.content IS NULL OR TRIM(ci.content) = '')
      AND ci.source_document_id IS NOT NULL
      AND ci.source_document_id NOT IN (
          SELECT iql.source_document_id
          FROM ingestion_quality_log iql
          WHERE iql.flag_type = 'missing_content'
            AND iql.resolved = FALSE
            AND iql.source_document_id IS NOT NULL
      )
    ORDER BY ci.source_document_id, ci.id;

    GET DIAGNOSTICS v_empty_content_flagged = ROW_COUNT;

    -- Return summary
    RETURN QUERY VALUES
        ('missing_domain_classification', v_missing_domain, v_missing_domain_flagged),
        ('low_confidence_classification', v_low_confidence, v_low_confidence_flagged),
        ('empty_string_source_url_fixed', v_empty_source_url, 0::BIGINT),
        ('empty_content', v_empty_content, v_empty_content_flagged);
END;
$$;

COMMENT ON FUNCTION "public"."run_quality_scan"("p_batch_name" "text") IS 'ID-131 {131.32} G-PRE-APPLY-131.13: re-pointed off the dying ingestion_quality_log.content_item_id (renamed to source_document_id by {131.13}) onto ci.source_document_id for all three INSERT branches and their dedup-guard subqueries. DISTINCT ON (ci.source_document_id) added to each branch to prevent duplicate flag rows within one scan run when multiple content_items share a source_document_id (many-to-one post-{131.13}). Content items with no backing source document are skipped (no valid document to record the flag against). Zero live TS/RPC callers as of this migration (dormant — fixed as a latent-defect precaution, not for an active caller). RETURNS TABLE shape unchanged.';

REVOKE ALL ON FUNCTION "public"."run_quality_scan"("p_batch_name" "text") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."run_quality_scan"("p_batch_name" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_quality_scan"("p_batch_name" "text") TO "service_role";
