-- ID-68.21 — drop the superseded client-named sign-up auth hook.
--
-- Liam repointed the live Before-User-Created auth hook (staging + prod) to the
-- generic, config-driven hook (hook_restrict_signup_to_allowed_domain, migration
-- 20260603121652). The superseded client-named function — created in migration
-- 20260424202806 — is now orphaned; drop it.
--
-- Replay-safe: 20260424202806 CREATEs the function (so a project reset /
-- branch-from-migrations restores it); this later migration removes it again,
-- leaving the generic hook as the only sign-up gate. IF EXISTS keeps the drop
-- idempotent across reset / rebase / the planned wipe-and-recut from the ID-45
-- re-ingest branch.
--
-- The superseded function's name + body are themselves client-identifying source
-- in migration history (20260424202806); redacting them — including the name in
-- the DROP below, in lockstep — is the ID-68.10 / {68.29} history lane's job
-- (out of scope here). Types regen for the removed hook happens at the DB cutover.
--
-- Reference: docs/reference/auth-hooks.md ; ID-68 TECH §PC-39(i).

DROP FUNCTION IF EXISTS public.hook_restrict_signup_to_example-client_domain(jsonb);
