-- =============================================================================
-- ID-115 (GAP A extension) — wrap three more missing api RPCs (append-only delta)
-- =============================================================================
--
-- A second batch of public RPCs that were live `.rpc()` call-sites but never
-- added to the generator's RPC surface (scripts/generate-api-views.ts), so they
-- were absent from api.* after the schema-isolation cutover. Because every
-- client (app, test, eval) threads DB_OPTION → routes `.rpc('x')` to `api.x` at
-- runtime (ID-115 S9), each call resolved to an absent `api.<fn>` → PGRST202:
--
--   - api.get_content_owner_stats       — content-owner stats route
--                                         GET /api/content-owners/stats.
--   - api.search_for_form_response      — procurement question-match route
--                                         (and the supersession-filter integration
--                                         suite). Two call shapes: with and
--                                         without include_superseded — both bind
--                                         to the single 5-arg signature by name.
--   - api._test_insert_broken_auth_user — integration suite serviceClient probe
--                                         insert (admin-users.integration S156/S157).
--
-- This is an APPEND-ONLY delta (sibling of 20260616140000): the generator's fixed
-- OUTPUT_FILE (20260616120100) is already applied to remotes and a changed applied
-- migration never re-applies, so the new wrappers ship here. The OUTPUT_FILE is
-- ALSO regenerated to the 72-fn superset in the same commit so
-- `generate-api-views.ts --check` (api-grant-guard.yml) stays green and a FRESH
-- replay produces a byte-identical catalog; the DROP/CREATE wrappers below are
-- idempotent, so re-running this after the regenerated OUTPUT_FILE on a fresh
-- environment is a harmless no-op redefine.
--
-- All three are thin SECURITY INVOKER wrappers (LANGUAGE sql,
-- SET search_path = public, extensions) delegating to public.<fn>; the wrappers
-- mirror each public original's role grants (REVOKE EXECUTE FROM PUBLIC then
-- GRANT to exactly those roles). _test_insert_broken_auth_user is a SECURITY
-- DEFINER public helper whose privileged body keeps running as postgres inside
-- public; the wrapper is INVOKER and granted ONLY to service_role (anon revoked),
-- mirroring its already-shipped _test_delete_broken_auth_user sibling — no anon
-- exposure. get_content_owner_stats and search_for_form_response are plain
-- INVOKER entrypoints granted to authenticated + service_role.
--
-- Generated by scripts/generate-api-views.ts (the blocks below are the exact
-- generator output for these three names); do not hand-edit — regenerate.
--
-- Spec: specs/id-115-data-api-schema-isolation TECH (g) / INV-6,10,16,20.
-- =============================================================================

-- Pin the search_path for the transaction so unqualified type refs (notably
-- `vector`, which lives in `extensions`) resolve at CREATE time regardless of
-- the connecting role (matches 20260616120100 / 20260616140000).
SET search_path = public, extensions;

-- api._test_insert_broken_auth_user(probe_id uuid, probe_email text)  [INVOKER wrapper over SECURITY DEFINER public fn]
DROP FUNCTION IF EXISTS api._test_insert_broken_auth_user(probe_id uuid, probe_email text);
CREATE FUNCTION api._test_insert_broken_auth_user(probe_id uuid, probe_email text)
  RETURNS void
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT public._test_insert_broken_auth_user(probe_id => probe_id, probe_email => probe_email);
$api$;
REVOKE EXECUTE ON FUNCTION api._test_insert_broken_auth_user(probe_id uuid, probe_email text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api._test_insert_broken_auth_user(probe_id uuid, probe_email text) TO service_role;

-- api.get_content_owner_stats()  [INVOKER entrypoint]
DROP FUNCTION IF EXISTS api.get_content_owner_stats();
CREATE FUNCTION api.get_content_owner_stats()
  RETURNS TABLE(owner_id uuid, total_items integer, fresh_count integer, aging_count integer, stale_count integer, expired_count integer, unverified_count integer)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.get_content_owner_stats();
$api$;
REVOKE EXECUTE ON FUNCTION api.get_content_owner_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.get_content_owner_stats() TO authenticated, service_role;

-- api.search_for_form_response(query_embedding vector, query_text text, limit_count integer, include_superseded boolean, visibility_filter character varying)  [INVOKER entrypoint]
DROP FUNCTION IF EXISTS api.search_for_form_response(query_embedding vector, query_text text, limit_count integer, include_superseded boolean, visibility_filter character varying);
CREATE FUNCTION api.search_for_form_response(query_embedding vector, query_text text DEFAULT ''::text, limit_count integer DEFAULT 10, include_superseded boolean DEFAULT false, visibility_filter character varying DEFAULT 'default'::character varying)
  RETURNS TABLE(id uuid, title text, content text, brief text, detail text, primary_domain character varying, primary_subtopic character varying, content_type character varying, ai_keywords text[], similarity numeric)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.search_for_form_response(query_embedding => query_embedding, query_text => query_text, limit_count => limit_count, include_superseded => include_superseded, visibility_filter => visibility_filter);
$api$;
REVOKE EXECUTE ON FUNCTION api.search_for_form_response(query_embedding vector, query_text text, limit_count integer, include_superseded boolean, visibility_filter character varying) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.search_for_form_response(query_embedding vector, query_text text, limit_count integer, include_superseded boolean, visibility_filter character varying) TO authenticated, service_role;
