-- ID-131.19 fix-Executor escalation 2 + 2b (S450 Wave 1) — coverage_retire:
-- drop the 3 content_items-shaped coverage RPCs per DR-034 (owner ruling).
--
-- APPLIED — landed via the owner-gated {131.19} GO sequence, AFTER
-- facet-mint (20260706100000) and BEFORE M6
-- (20260706110000_id131_drops.sql, which drops the `content_items` table
-- itself). Confirmed live on platform staging (version 20260706104000 is in
-- the applied-migrations list). Sequencing note: dropping these three
-- functions had no ordering dependency on the M6 content_items drop (a
-- `LANGUAGE sql` function body is not catalog-bound to the tables it queries
-- the way a view is — DROP FUNCTION never fails and DROP TABLE never fails
-- because of this file either way), but the {131.19} GO applied this one
-- first per the owner's sequencing note in the dispatch brief.
--
-- ============================================================================
-- WHY — DR-034 (owner ruling, binding, cited verbatim from the fix-Executor
-- dispatch brief): "the content_items-era coverage feature (matrix/summary/
-- routes/cron) is RETIRED, not re-pointed; retain template-completion
-- coverage + governance signals only."
--
-- M6's own header (20260706110000_id131_drops.sql, escalation item 2)
-- documented `get_coverage_matrix(p_layer)` / `get_coverage_summary()` as
-- entirely content_items-shaped (LEFT JOIN content_items on
-- primary_domain/primary_subtopic/publication_status/freshness) and flagged
-- them as needing a product-level decision BEFORE the content_items drop
-- applies, since 3 TS callers would otherwise start erroring at their next
-- call: app/api/coverage/route.ts, app/api/coverage/gaps/route.ts (its
-- taxonomy-gap source only — its template-gap source is unrelated and
-- survives via a route deletion, not a stub), and the unattended
-- app/api/cron/coverage-alerts/route.ts cron. DR-034 resolves that
-- open question as RETIREMENT: this Subtask deletes all three TS callers
-- (plus their supporting UI: the taxonomy/priority-gaps/guides tabs) in the
-- same commit as this migration, so by apply time there is no live caller
-- left to error. The surviving `/coverage` page renders only the
-- template-completion tab (`template-coverage-content.tsx`, already
-- re-pointed off content_items onto q_a_pairs/reference_items by an earlier
-- {131} Subtask — no RPC dependency, unaffected by this drop).
--
-- ESCALATION 2 surfaced `get_guide_coverage()` (public + api) as a FOURTH
-- content_items-shaped RPC (LEFT JOIN content_items on primary_domain/
-- primary_subtopic/layer/content_type/publication_status — structurally
-- identical to get_coverage_matrix) that would ALSO start erroring post-M6.
-- Its escalation-2 in-boundary callers (app/api/coverage/guides/route.ts and
-- the guide-gap source in app/api/coverage/gaps/route.ts) were deleted in
-- escalation 2's commit, per the same DR-034 content_items-era
-- classification — but app/api/guides/route.ts (OUTSIDE escalation 2's
-- file-ownership boundary) also called `supabase.rpc('get_guide_coverage')`
-- and remained live, so the function itself could not be dropped there.
--
-- ESCALATION 2b (this commit) resolves that open question: the owner ruled
-- guide-coverage stats are content_items-era, not a governance signal to
-- re-point — RETIRE, matching escalation 2's disposition. The
-- `?include=stats` leg of app/api/guides/route.ts (its only caller of
-- `get_guide_coverage`) has been removed in the same commit as this
-- migration edit; the guide-listing/creation route itself survives
-- unchanged. With no live caller left in either schema-surface,
-- `get_guide_coverage()` is now safe to drop alongside the original two
-- RPCs below.
-- ============================================================================
--
-- WHAT: drop `get_coverage_matrix(p_layer)` / `get_coverage_summary()` /
-- `get_guide_coverage()` in BOTH the `api` (Data API wrapper, INVOKER
-- entrypoint) and `public` (backing implementation) schemas, exact
-- signatures pulled from the last whole-surface regen
-- (20260625160000_id130_api_views_regen.sql) / baseline
-- (20260617130000_squash_baseline.sql) — identical signatures across both.
-- Dependents (api wrappers) dropped before their base (public) objects,
-- mirroring M6's own ordering convention. Idempotent (`IF EXISTS`) and
-- safely re-runnable.
--
-- Companion generator edit: `get_coverage_matrix` / `get_coverage_summary` /
-- `get_guide_coverage` removed from SURFACE_RPCS in
-- scripts/generate-api-views.ts (escalation 2 + 2b commits) so the next
-- whole-surface regen does not resurrect the api.* wrappers this migration
-- drops.

-- STEP 1 — drop the api.* wrapper (INVOKER entrypoint) for all three functions.
DROP FUNCTION IF EXISTS api.get_coverage_matrix(p_layer text);
DROP FUNCTION IF EXISTS api.get_coverage_summary();
DROP FUNCTION IF EXISTS api.get_guide_coverage();

-- STEP 2 — drop the public.* backing implementation for all three functions.
DROP FUNCTION IF EXISTS public.get_coverage_matrix(p_layer text);
DROP FUNCTION IF EXISTS public.get_coverage_summary();
DROP FUNCTION IF EXISTS public.get_guide_coverage();
