-- ID-131.10 (G-CITE-WINRATE) — M4b: citation contract extension + win-rate fix.
-- TECH.md §Migration set row M4b + §"The 3 win-rate function rewrites (M4b)" +
-- §Function disposition (update_citation_count). PRODUCT.md BI-23/BI-24/BI-25/BI-26.
--
-- Atomic-at-deploy (BI-24): the enum (M4a, prior txn), the CHECK, the new columns,
-- and all three win-rate functions move together. Data-safe: citations = 0 rows, so
-- no live citation can orphan during the change.
--
-- This migration:
--   1. ADDs the three new cited_*_id / cited_concept_path columns.
--   2. Rewrites citations_cited_one_of_chk to enforce exactly-one across all 5 kinds.
--   3. Rewrites the 3 win-rate fns (get_content_win_rate, get_aggregate_win_rate_stats,
--      hybrid_search.win_stats — Slice A) onto the q_a_pair anchor + the single
--      canonical outcome source form_outcome_types.counts_toward_win_rate (BI-25).
--   4. DROPs the update_citation_count trigger + function (citation_count is derived,
--      not stored — BI-20; default disposition per TECH §Function disposition).
--
-- DEFERRED (NOT here): the cited_content_item_id COLUMN drop + the dead content_item
-- enum LABEL drop (M6/G-API); the api.* wrapper regen for api.citations /
-- api.get_content_win_rate (signature change → G-API pre-drops the old wrapper) /
-- api.get_aggregate_win_rate_stats / api.hybrid_search (all G-API / ID-131.19); the
-- hybrid_search polymorphic UNION body (Slice B, M5 / ID-131.11).

-- ============================================================================
-- 1. New citation target columns (BI-23 — CITE-EXT).
-- DB-record targets use the §B record uuid (FK + ON DELETE CASCADE); concept targets
-- use the concept path (text, no FK — concepts are a namespaced path, not a table row).
-- ============================================================================
ALTER TABLE "public"."citations"
  ADD COLUMN "cited_reference_item_id" "uuid" REFERENCES "public"."reference_items"("id") ON DELETE CASCADE,
  ADD COLUMN "cited_source_document_id" "uuid" REFERENCES "public"."source_documents"("id") ON DELETE CASCADE,
  ADD COLUMN "cited_concept_path" "text";

-- ============================================================================
-- 2. Exactly-one-of CHECK across all 5 kinds (BI-23). Preserves the squash-baseline
-- idiom (enum-cast literals, per-kind branch); each branch requires its own target
-- column NON-NULL and ALL other target columns NULL.
-- ============================================================================
ALTER TABLE "public"."citations" DROP CONSTRAINT IF EXISTS "citations_cited_one_of_chk";
ALTER TABLE "public"."citations" ADD CONSTRAINT "citations_cited_one_of_chk" CHECK (
  (("cited_kind" = 'content_item'::"public"."cited_target_kind")
    AND ("cited_content_item_id" IS NOT NULL)
    AND ("cited_q_a_pair_id" IS NULL) AND ("cited_reference_item_id" IS NULL)
    AND ("cited_source_document_id" IS NULL) AND ("cited_concept_path" IS NULL))
  OR (("cited_kind" = 'q_a_pair'::"public"."cited_target_kind")
    AND ("cited_q_a_pair_id" IS NOT NULL)
    AND ("cited_content_item_id" IS NULL) AND ("cited_reference_item_id" IS NULL)
    AND ("cited_source_document_id" IS NULL) AND ("cited_concept_path" IS NULL))
  OR (("cited_kind" = 'reference_item'::"public"."cited_target_kind")
    AND ("cited_reference_item_id" IS NOT NULL)
    AND ("cited_content_item_id" IS NULL) AND ("cited_q_a_pair_id" IS NULL)
    AND ("cited_source_document_id" IS NULL) AND ("cited_concept_path" IS NULL))
  OR (("cited_kind" = 'source_document'::"public"."cited_target_kind")
    AND ("cited_source_document_id" IS NOT NULL)
    AND ("cited_content_item_id" IS NULL) AND ("cited_q_a_pair_id" IS NULL)
    AND ("cited_reference_item_id" IS NULL) AND ("cited_concept_path" IS NULL))
  OR (("cited_kind" = 'concept'::"public"."cited_target_kind")
    AND ("cited_concept_path" IS NOT NULL)
    AND ("cited_content_item_id" IS NULL) AND ("cited_q_a_pair_id" IS NULL)
    AND ("cited_reference_item_id" IS NULL) AND ("cited_source_document_id" IS NULL))
);

-- ============================================================================
-- 3a. public.get_content_win_rate — re-anchor content_item -> q_a_pair (BI-26).
-- The arg is RENAMED p_content_item_id -> p_q_a_pair_id, so CREATE OR REPLACE is
-- impossible (42P13 "cannot change name of input parameter"): DROP then CREATE. The
-- api.get_content_win_rate wrapper (string-body SQL fn) holds no hard dependency, so
-- the DROP is clean; the wrapper is regenerated by G-API (ID-131.19, which pre-drops
-- the old signature). Return shape is PRESERVED (total/winning/losing/pending/win_rate)
-- and the counts_toward_win_rate=true denominator (id-130 final-award-only gate) is KEPT.
-- ============================================================================
DROP FUNCTION IF EXISTS "public"."get_content_win_rate"("uuid");

CREATE FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid")
    RETURNS TABLE("total_citations" bigint, "winning_citations" bigint, "losing_citations" bigint, "pending_citations" bigint, "win_rate" numeric)
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'extensions'
    AS $$
BEGIN
  RETURN QUERY
  WITH "citation_outcomes" AS (
    SELECT
      "cc"."cited_q_a_pair_id",
      "cc"."citing_form_response_id",
      "ft"."outcome"                    AS "outcome",
      "fot"."counts_toward_win_rate"    AS "counts_toward_win_rate"
    FROM "public"."citations" "cc"
    JOIN "public"."form_responses" "br" ON "br"."id" = "cc"."citing_form_response_id"
    JOIN "public"."form_questions" "fq" ON "fq"."id" = "br"."question_id"
    JOIN "public"."form_templates" "ft" ON "ft"."id" = "fq"."form_template_id"
    LEFT JOIN "public"."form_outcome_types" "fot" ON "fot"."key" = "ft"."outcome"
    WHERE "cc"."cited_kind" = 'q_a_pair'
      AND "cc"."cited_q_a_pair_id" = "p_q_a_pair_id"
  )
  SELECT
    COUNT(*)::bigint AS "total_citations",
    COUNT(*) FILTER (WHERE "co"."outcome" = 'won')::bigint AS "winning_citations",
    COUNT(*) FILTER (WHERE "co"."outcome" = 'lost')::bigint AS "losing_citations",
    -- pending = NOT in the win-rate denominator (no counts_toward_win_rate=true outcome yet).
    COUNT(*) FILTER (WHERE COALESCE("co"."counts_toward_win_rate", false) = false)::bigint AS "pending_citations",
    CASE
      WHEN COUNT(*) FILTER (WHERE "co"."counts_toward_win_rate" = true) > 0 THEN
        ROUND(
          COUNT(*) FILTER (WHERE "co"."outcome" = 'won')::numeric /
          COUNT(*) FILTER (WHERE "co"."counts_toward_win_rate" = true)::numeric,
          2
        )
      ELSE 0
    END AS "win_rate"
  FROM "citation_outcomes" "co";
END;
$$;

ALTER FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") OWNER TO "postgres";

-- Match the id-130 least-privilege posture (authenticated + service_role; no anon).
REVOKE ALL ON FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") FROM "anon";
GRANT ALL ON FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") TO "service_role";

COMMENT ON FUNCTION "public"."get_content_win_rate"("p_q_a_pair_id" "uuid") IS 'ID-131.10 BI-26 — per-q_a_pair citation win-rate (re-anchored from content_item). CTE joins citations -> form_responses -> form_questions -> form_templates and LEFT JOINs form_outcome_types on ft.outcome; win-rate denominator is the CV flag counts_toward_win_rate=true (kept from id-130). Predicate cited_kind=q_a_pair AND cited_q_a_pair_id=$1. Return shape unchanged (total/winning/losing/pending/win_rate).';

-- ============================================================================
-- 3b. public.get_aggregate_win_rate_stats — drop the content_items JOIN; scope by
-- record_lifecycle.domain for owner_kind='q_a_pair' (Finding 2: q_a_pairs have no
-- primary_domain — the domain lives on the facet, synced by ID-131.9 M3-trig); key on
-- cited_q_a_pair_id. The counts_toward_win_rate denominator + the stage='shortlist'
-- pass-rate block are KEPT. Return shape is UNCHANGED (11 cols) so a plain CREATE OR
-- REPLACE suffices — no DROP-dance, and the api wrapper stays valid (regen by G-API).
-- LEFT JOIN to the facet so a q_a_pair citation whose owner has no facet row still
-- counts (scope NULL), preserving cardinality.
-- ============================================================================
CREATE OR REPLACE FUNCTION "public"."get_aggregate_win_rate_stats"()
    RETURNS TABLE("scope" "text", "total_citations" bigint, "winning_citations" bigint, "losing_citations" bigint, "pending_citations" bigint, "win_rate" numeric, "unique_items_cited" bigint, "unique_procurements" bigint, "shortlist_total" bigint, "shortlist_passed" bigint, "shortlist_pass_rate" numeric)
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public', 'extensions'
    AS $$
BEGIN
  RETURN QUERY

  WITH "citation_detail" AS (
    SELECT
      "rl"."domain"                     AS "primary_domain",
      "cc"."cited_q_a_pair_id",
      "cc"."citing_form_response_id",
      "ft"."workspace_id",
      "ft"."outcome"                    AS "outcome",
      "fot"."counts_toward_win_rate"    AS "counts_toward_win_rate",
      "fot"."stage"                     AS "outcome_stage"
    FROM "public"."citations" "cc"
    JOIN "public"."form_responses" "br" ON "br"."id" = "cc"."citing_form_response_id"
    JOIN "public"."form_questions" "fq" ON "fq"."id" = "br"."question_id"
    JOIN "public"."form_templates" "ft" ON "ft"."id" = "fq"."form_template_id"
    LEFT JOIN "public"."form_outcome_types" "fot" ON "fot"."key" = "ft"."outcome"
    LEFT JOIN "public"."record_lifecycle" "rl"
      ON "rl"."owner_kind" = 'q_a_pair' AND "rl"."owner_id" = "cc"."cited_q_a_pair_id"
    WHERE "cc"."cited_kind" = 'q_a_pair'
  ),
  "domain_stats" AS (
    SELECT
      "cd"."primary_domain" AS "scope",
      COUNT(*)::bigint AS "total_citations",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'won')::bigint AS "winning_citations",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'lost')::bigint AS "losing_citations",
      COUNT(*) FILTER (WHERE COALESCE("cd"."counts_toward_win_rate", false) = false)::bigint AS "pending_citations",
      CASE
        WHEN COUNT(*) FILTER (WHERE "cd"."counts_toward_win_rate" = true) > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE "cd"."outcome" = 'won')::numeric /
            COUNT(*) FILTER (WHERE "cd"."counts_toward_win_rate" = true)::numeric,
            2
          )
        ELSE 0
      END AS "win_rate",
      COUNT(DISTINCT "cd"."cited_q_a_pair_id")::bigint AS "unique_items_cited",
      COUNT(DISTINCT "cd"."workspace_id")::bigint AS "unique_procurements",
      -- Separate shortlist pass-rate (stage='shortlist'): total = shortlisted+not_shortlisted,
      -- passed = shortlisted. Excludes final-award citations entirely.
      COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist')::bigint AS "shortlist_total",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'shortlisted')::bigint AS "shortlist_passed",
      CASE
        WHEN COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist') > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE "cd"."outcome" = 'shortlisted')::numeric /
            COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist')::numeric,
            2
          )
        ELSE 0
      END AS "shortlist_pass_rate"
    FROM "citation_detail" "cd"
    GROUP BY "cd"."primary_domain"
  ),
  "overall" AS (
    SELECT
      'overall'::"text" AS "scope",
      COUNT(*)::bigint AS "total_citations",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'won')::bigint AS "winning_citations",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'lost')::bigint AS "losing_citations",
      COUNT(*) FILTER (WHERE COALESCE("cd"."counts_toward_win_rate", false) = false)::bigint AS "pending_citations",
      CASE
        WHEN COUNT(*) FILTER (WHERE "cd"."counts_toward_win_rate" = true) > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE "cd"."outcome" = 'won')::numeric /
            COUNT(*) FILTER (WHERE "cd"."counts_toward_win_rate" = true)::numeric,
            2
          )
        ELSE 0
      END AS "win_rate",
      COUNT(DISTINCT "cd"."cited_q_a_pair_id")::bigint AS "unique_items_cited",
      COUNT(DISTINCT "cd"."workspace_id")::bigint AS "unique_procurements",
      COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist')::bigint AS "shortlist_total",
      COUNT(*) FILTER (WHERE "cd"."outcome" = 'shortlisted')::bigint AS "shortlist_passed",
      CASE
        WHEN COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist') > 0 THEN
          ROUND(
            COUNT(*) FILTER (WHERE "cd"."outcome" = 'shortlisted')::numeric /
            COUNT(*) FILTER (WHERE "cd"."outcome_stage" = 'shortlist')::numeric,
            2
          )
        ELSE 0
      END AS "shortlist_pass_rate"
    FROM "citation_detail" "cd"
  )
  SELECT * FROM "overall"
  UNION ALL
  SELECT * FROM "domain_stats"
  ORDER BY "scope";
END;
$$;

ALTER FUNCTION "public"."get_aggregate_win_rate_stats"() OWNER TO "postgres";

REVOKE ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."get_aggregate_win_rate_stats"() FROM "anon";
GRANT ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_aggregate_win_rate_stats"() TO "service_role";

COMMENT ON FUNCTION "public"."get_aggregate_win_rate_stats"() IS 'ID-131.10 BI-26 — overall + per-domain citation win-rate aggregator, re-anchored content_item -> q_a_pair. Drops the content_items JOIN; scope = record_lifecycle.domain for owner_kind=q_a_pair (Finding 2 — facet-synced domain, ID-131.9 M3-trig); keyed on cited_q_a_pair_id. Win-rate denominator is counts_toward_win_rate=true (kept from id-130); shortlist pass-rate block kept. Return shape unchanged. Caller app/api/analytics/win-rate.';

-- ============================================================================
-- 3c. public.hybrid_search — win_stats CTE re-point (Slice A, BI-25/BI-26).
-- EDIT SCOPE: the win_stats CTE ONLY. The rest of the function body (which still
-- scans content_items) is owned by Slice B (M5 / ID-131.11) and is reproduced here
-- VERBATIM so the CREATE OR REPLACE stays a no-op on it. Signature + return shape are
-- unchanged. The win signal now sources win/loss from the single canonical source
-- form_outcome_types.counts_toward_win_rate (BI-25) — the workspaces.domain_metadata
-- join is REMOVED — and is q_a_pair-anchored (BI-26). See the CTE comment for why the
-- output column keeps the name content_item_id (body-join validity) and why
-- content_items therefore receive no win boost in this intermediate Slice-A state.
-- ============================================================================
CREATE OR REPLACE FUNCTION "public"."hybrid_search"("query_embedding" "extensions"."vector", "query_text" "text" DEFAULT ''::"text", "similarity_threshold" numeric DEFAULT 0.3, "limit_count" integer DEFAULT 10, "include_superseded" boolean DEFAULT false, "visibility_filter" character varying DEFAULT 'default'::character varying) RETURNS TABLE("id" "uuid", "title" "text", "suggested_title" "text", "summary" "text", "primary_domain" "text", "primary_subtopic" "text", "content_type" "text", "platform" "text", "author_name" "text", "source_domain" "text", "thumbnail_url" "text", "captured_date" timestamp with time zone, "ai_keywords" "text"[], "classification_confidence" numeric, "priority" "text", "metadata" "jsonb", "similarity" numeric, "snippet" "text", "created_by" "uuid", "verified_at" timestamp with time zone, "verified_by" "uuid")
    LANGUAGE "plpgsql" STABLE
    SET "search_path" TO 'public', 'extensions'
    AS $$
DECLARE
  win_boost CONSTANT numeric := 0.03;
  min_win_citations CONSTANT integer := 2;
BEGIN
  RETURN QUERY
  WITH win_stats AS (
    -- ID-131.10 Slice A (BI-25/BI-26): the win signal is now Q&A-anchored and sources
    -- win/loss from the single canonical source form_outcome_types.counts_toward_win_rate
    -- (the retired workspaces JSON outcome path is gone — no workspaces join). The output
    -- column is STILL aliased content_item_id purely so the unchanged body join below
    -- (LEFT JOIN win_stats ws ON ws.content_item_id = ci.id, where ci scans
    -- content_items) stays VALID — Slice B (M5 / ID-131.11) re-homes the body onto a
    -- polymorphic q_a_pair-aware UNION, at which point the join becomes meaningful.
    -- Until then this column holds cited_q_a_pair_id values, which never equal a
    -- content_items.id, so content_items receive NO win boost — intended: the win
    -- signal is a q_a_pair-only signal (BI-26); non-q_a_pair arms get no boost.
    SELECT cc.cited_q_a_pair_id AS content_item_id,
      COUNT(DISTINCT cc.citing_form_response_id)::integer AS total_citations,
      COUNT(DISTINCT cc.citing_form_response_id) FILTER (
        WHERE fot.counts_toward_win_rate = true AND ft.outcome = 'won'
      )::numeric / NULLIF(
        COUNT(DISTINCT cc.citing_form_response_id) FILTER (WHERE fot.counts_toward_win_rate = true),
        0
      ) AS win_rate
    FROM public.citations cc
    JOIN form_responses br ON br.id = cc.citing_form_response_id
    JOIN form_questions fq ON fq.id = br.question_id
    JOIN form_templates ft ON ft.id = fq.form_template_id
    LEFT JOIN form_outcome_types fot ON fot.key = ft.outcome
    WHERE cc.cited_kind = 'q_a_pair'
    GROUP BY cc.cited_q_a_pair_id
  )
  SELECT
    ci.id, ci.title, ci.suggested_title, ci.summary,
    ci.primary_domain::text, ci.primary_subtopic::text, ci.content_type::text, ci.platform::text,
    ci.author_name::text, ci.source_domain::text, ci.thumbnail_url, ci.captured_date,
    ci.ai_keywords, ci.classification_confidence, ci.priority::text, ci.metadata,
    LEAST(1.0, (
      (1 - (ci.embedding <=> query_embedding)) * 0.70
      + CASE WHEN ci.suggested_title ILIKE '%' || query_text || '%' THEN 0.15
             WHEN ci.title ILIKE '%' || query_text || '%' THEN 0.15
             ELSE 0.0 END
      + CASE WHEN query_text = ANY(ci.ai_keywords) THEN 0.10
             WHEN EXISTS (SELECT 1 FROM unnest(ci.ai_keywords) AS kw WHERE kw ILIKE '%' || query_text || '%') THEN 0.05
             ELSE 0.0 END
      + CASE WHEN ci.summary ILIKE '%' || query_text || '%' THEN 0.03 ELSE 0.0 END
      + CASE WHEN ci.author_name ILIKE '%' || query_text || '%' THEN 0.02 ELSE 0.0 END
      + CASE WHEN ci.captured_date IS NOT NULL AND ci.captured_date > NOW() - INTERVAL '30 days'
             THEN 0.05 * (1.0 - EXTRACT(EPOCH FROM (NOW() - ci.captured_date)) / (30.0 * 86400.0))
             ELSE 0.0 END
    ) * CASE
        WHEN COALESCE(ws.total_citations, 0) >= min_win_citations
        THEN (1.0 + win_boost * COALESCE(ws.win_rate, 0.0))
        ELSE 1.0
      END
    )::NUMERIC(4, 3) AS similarity,
    CASE WHEN query_text IS NOT NULL AND query_text != '' AND ci.content IS NOT NULL
         AND position(lower(query_text) IN lower(ci.content)) > 0
         THEN substring(ci.content FROM greatest(1, position(lower(query_text) IN lower(ci.content)) - 80) FOR 200)
         ELSE NULL END AS snippet,
    ci.created_by,
    ci.verified_at,
    ci.verified_by
  FROM content_items ci
  LEFT JOIN win_stats ws ON ws.content_item_id = ci.id
  WHERE ci.embedding IS NOT NULL
    AND (include_superseded OR ci.superseded_by IS NULL)
    AND CASE visibility_filter
          WHEN 'default' THEN ci.publication_status = 'published'
          WHEN 'all' THEN ci.publication_status != 'archived'
          WHEN 'admin' THEN TRUE
          ELSE ci.publication_status = 'published'
        END
    AND (
      (1 - (ci.embedding <=> query_embedding)) > similarity_threshold
      OR (
        query_text IS NOT NULL AND query_text != '' AND (
          ci.suggested_title ILIKE '%' || query_text || '%'
          OR ci.title ILIKE '%' || query_text || '%'
          OR ci.content ILIKE '%' || query_text || '%'
        )
      )
    )
  ORDER BY similarity DESC
  LIMIT limit_count;
END;
$$;

COMMENT ON FUNCTION "public"."hybrid_search"("query_embedding" "extensions"."vector", "query_text" "text", "similarity_threshold" numeric, "limit_count" integer, "include_superseded" boolean, "visibility_filter" character varying) IS 'S216 W3 §5.2 Phase 3 + ID-197 + ID-131.10 Slice A: hybrid full-text + vector search with visibility_filter. ID-131.10 (BI-25/BI-26) re-points the win_stats CTE off the retired workspaces JSON outcome path onto the single canonical outcome source form_outcome_types.counts_toward_win_rate and re-anchors it content_item -> q_a_pair (cited_q_a_pair_id). The UNION/body polymorphic rewrite is Slice B (M5 / ID-131.11); content_items receive no win boost in this intermediate state (q_a_pair-only win signal).';

-- ============================================================================
-- 4. update_citation_count disposition: DROP (TECH §Function disposition; BI-20).
-- citation_count is a DERIVED value, not stored. This SECDEF trigger maintained a
-- stored public.content_items.citation_count; content_items is slated for DROP
-- (M6/G-API) and no SURVIVING table carries a stored citation count to maintain
-- (q_a_pairs has no citation_count column). gitnexus_impact: not a code-graph node
-- (trigger fn). The remaining TS reads of content_items.citation_count are
-- stale-tolerant display reads (removed/retired alongside the content_items table
-- drop), so dropping the maintenance trigger orphans nothing live. Drop the two
-- bound triggers first, then the function.
-- ============================================================================
DROP TRIGGER IF EXISTS "trg_citation_count_insert" ON "public"."citations";
DROP TRIGGER IF EXISTS "trg_citation_count_delete" ON "public"."citations";
DROP FUNCTION IF EXISTS "public"."update_citation_count"();
