-- =============================================================================
-- ID-115 (GAP A) — add four missing api RPC wrappers (append-only delta)
-- =============================================================================
--
-- Four public RPCs were live `.rpc()` call-sites but were never added to the
-- generator's RPC surface (scripts/generate-api-views.ts), so they were absent
-- from api.* after the schema-isolation cutover. Because every client (app,
-- test, eval) threads DB_OPTION → routes `.rpc('x')` to `api.x` at runtime
-- (ID-115 S9), each call resolved to an absent `api.<fn>` → PGRST202:
--
--   - api.find_duplicate_pairs          — MCP dedup tool + admin near-duplicates
--                                         route (eval-l4 FC-44).
--   - api.get_content_win_rate          — item effectiveness route + procurement
--                                         MCP tool (eval-l4 FC-51).
--   - api.get_guide_content             — guide detail route GET /api/guides/[slug]
--                                         (e2e guide-pages.spec guide-detail tests).
--   - api._test_delete_broken_auth_user — integration suite serviceClient cleanup
--                                         (admin-users.integration + others).
--
-- This is an APPEND-ONLY delta: 20260616120100_id115_api_views_and_rpcs.sql is
-- already applied to remotes and a changed applied migration never re-applies,
-- so the four new wrappers ship here. The generator's fixed OUTPUT_FILE
-- (20260616120100) is ALSO regenerated to the 69-fn superset in the same commit
-- so `generate-api-views.ts --check` (api-grant-guard.yml) stays green and a
-- FRESH replay produces a byte-identical catalog; the DROP/CREATE wrappers below
-- are idempotent, so re-running this after the regenerated OUTPUT_FILE on a fresh
-- environment is a harmless no-op redefine.
--
-- All four are thin SECURITY INVOKER wrappers (LANGUAGE sql,
-- SET search_path = public, extensions) delegating to public.<fn>; the wrappers
-- mirror each public original's role grants (REVOKE EXECUTE FROM PUBLIC then
-- GRANT to exactly those roles). _test_delete_broken_auth_user is a SECURITY
-- DEFINER public helper whose privileged body keeps running as postgres inside
-- public; the wrapper is INVOKER and granted ONLY to service_role (anon revoked),
-- mirroring the already-shipped api.count_auth_users sibling — no anon exposure.
--
-- Generated by scripts/generate-api-views.ts (the blocks below are the exact
-- generator output for these four names); do not hand-edit — regenerate.
--
-- Spec: specs/id-115-data-api-schema-isolation TECH (g) / INV-6,10,16,20.
-- =============================================================================

-- Pin the search_path for the transaction so unqualified type refs resolve at
-- CREATE time regardless of the connecting role (matches 20260616120100).
SET search_path = public, extensions;

-- api._test_delete_broken_auth_user(probe_id uuid)  [INVOKER wrapper over SECURITY DEFINER public fn]
DROP FUNCTION IF EXISTS api._test_delete_broken_auth_user(probe_id uuid);
CREATE FUNCTION api._test_delete_broken_auth_user(probe_id uuid)
  RETURNS void
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT public._test_delete_broken_auth_user(probe_id => probe_id);
$api$;
REVOKE EXECUTE ON FUNCTION api._test_delete_broken_auth_user(probe_id uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api._test_delete_broken_auth_user(probe_id uuid) TO service_role;

-- api.find_duplicate_pairs(similarity_threshold numeric, p_domain text, limit_count integer)  [INVOKER entrypoint]
DROP FUNCTION IF EXISTS api.find_duplicate_pairs(similarity_threshold numeric, p_domain text, limit_count integer);
CREATE FUNCTION api.find_duplicate_pairs(similarity_threshold numeric DEFAULT 0.95, p_domain text DEFAULT NULL::text, limit_count integer DEFAULT 50)
  RETURNS TABLE(id1 uuid, title1 text, type1 character varying, domain1 character varying, id2 uuid, title2 text, type2 character varying, domain2 character varying, similarity numeric)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.find_duplicate_pairs(similarity_threshold => similarity_threshold, p_domain => p_domain, limit_count => limit_count);
$api$;
REVOKE EXECUTE ON FUNCTION api.find_duplicate_pairs(similarity_threshold numeric, p_domain text, limit_count integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.find_duplicate_pairs(similarity_threshold numeric, p_domain text, limit_count integer) TO authenticated, service_role;

-- api.get_content_win_rate(p_content_item_id uuid)  [INVOKER entrypoint]
DROP FUNCTION IF EXISTS api.get_content_win_rate(p_content_item_id uuid);
CREATE FUNCTION api.get_content_win_rate(p_content_item_id uuid)
  RETURNS TABLE(total_citations bigint, winning_citations bigint, losing_citations bigint, pending_citations bigint, win_rate numeric)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.get_content_win_rate(p_content_item_id => p_content_item_id);
$api$;
REVOKE EXECUTE ON FUNCTION api.get_content_win_rate(p_content_item_id uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.get_content_win_rate(p_content_item_id uuid) TO authenticated, service_role;

-- api.get_guide_content(p_guide_slug text)  [INVOKER entrypoint]
DROP FUNCTION IF EXISTS api.get_guide_content(p_guide_slug text);
CREATE FUNCTION api.get_guide_content(p_guide_slug text)
  RETURNS TABLE(section_id uuid, section_name text, section_description text, section_order integer, expected_layer text, subtopic_filter text, is_required boolean, content_id uuid, content_title text, content_type text, content_layer text, content_brief text, content_freshness text, content_verified_at timestamp with time zone, content_captured_date timestamp with time zone)
  LANGUAGE sql
  SECURITY INVOKER
  SET search_path = public, extensions
AS $api$
  SELECT * FROM public.get_guide_content(p_guide_slug => p_guide_slug);
$api$;
REVOKE EXECUTE ON FUNCTION api.get_guide_content(p_guide_slug text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.get_guide_content(p_guide_slug text) TO authenticated, service_role;
